### ISSUE TITLE
Review list of bootstrap nodes

### ISSUE THREAD

**Issue by harry1453** [signum-network/signum-node#11]
At the moment all nodes listed as bootstrap must be using standard port (8123).

We also need to check the bootstrap list and add/remove as necessary.

**Comment by llybin** [comment]
Can take here, done: https://gist.github.com/llybin/05d002ab5347606f688f62cbad2427ea

**Comment by Zoh63392187** [comment]
That list needed to update again just before release.

**Comment by llybin** [comment]
https://explorer.burst.devtrue.net/peers/

`select announced_address from scan_peermonitor where availability > 90 and version = "v2.4.2" and height=705013 and created_at < "2019-09-01";`

108.238.244.144; 109.123.144.46; 123.3.107.89; 134.3.37.88; 188.68.41.245; 212.98.92.236; 213.123.226.246; 51.75.123.18; 54re.dynip.online; 71.203.119.113; 73.144.224.102; 75.100.126.226; 75.100.126.227; 75.100.126.228; 75.100.126.230; 77.66.65.240; 77.68.73.180; 80.241.221.231; 81.217.126.132; 81.237.255.75; 81.6.54.180; 81.83.5.50; 83.169.21.233; 84.10.50.53; 86.4.48.129; 91.121.70.43; 91.139.231.245; 96.35.124.185; 99.189.103.11; burst-fi.megash.it; burst-node.duckdns.org; burst.felixbrucker.com; burst.foxden.party; burst.megash.it; l6vz3inz6fv4dtnt.myfritz.net; muehli.zapto.org; octalsburstnode.ddns.net; storjserver.cryptomass.de; tordek.mine.nu; wallet.burst-alliance.org; wallet.burst.devtrue.net; wallet.smit.pro; wrrdte6tvjp2uvjp.ddns.net; wve8gz9mbp6ahx6t.ddns.net

They are all public, available on 8123 port, the latest main version, availability > 90, not stuck, known for long time.

**Comment by llybin** [comment]
if ok I will create PR

**Comment by jjos2372** [comment]
Reviewed.
