### ISSUE TITLE
Payout dividend window not really working

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#147]
The window for "Payout Dividend" is not working properly.
I can´t set a Dividend date nor an account i want to disclose.
All fields are greyed out and not selectable.

Also the fee is one BURST per account i need to send the dividend! 
As this is an ordinary payment i should be able to use the normal fee structure from BURST

![image](https://user-images.githubusercontent.com/39116221/58126564-7fb06400-7c13-11e9-96b5-c0043bc64f3b.png)

I use Version 2.3.0.
I tried via localhost and internal within the wallet - both show the same result

Can someone also check the query behind please - it is terrible slow take 3702027329806229573 as reference

**Comment by frankTheTank72** [comment]
@harry1453  are you Aware of this ? 
Will this be covered by your Kollin move ?

**Comment by shefass** [comment]
I looked to it already(some time ago), it is UI problem, not nodes. It just
uses JS script to count dividends.. I think now better just wait then
phoenix will have more functionality then fix this old.
And for a node, I think the command line is enough, no need GUI or need
very simple.


2019-09-21, št, 21:05 frankTheTank72 <notifications@github.com> rašė:

**Comment by frankTheTank72** [comment]
@shefass  thx for your comment ; but if we want to povide a user-friendly UI this should work without an "command-line" style for the masses.

Also in the current UI  you are unable to set the parameters

**Comment by shefass** [comment]
My opinion for the masses Phoenix, Hotwallet and other "third party"
wallets. For node is enough command-line, sure it is my opinion.

2019-09-21, št, 22:15 frankTheTank72 <notifications@github.com> rašė:

**Comment by jjos2372** [comment]
This is available on BTDEX and there is a new API in the development version.
