### ISSUE TITLE
New API call with filter criteria for AT selection

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#150]
Atm we can only request for AT-IDs in general via http://at-testnet.burst-alliance.org:6876/burst?requestType=getATIds

If we will have in the near future more ATs on the chain, we should be able to give filter criteria  within a new call to get a pre-filtered AT-ID list.

The maximum details for an ATS are the following:

{
    "creator": "5219831338759933722",
    "creatorRS": "BURST-TMSU-YBH5-RVC7-6J6WJ",
    "at": "15869142951140617004",
    "atRS": "BURST-4UTE-FY8C-PSUE-F7NGS",
    "atVersion": 2,
    "name": "OddsGame1557668323155",
    "description": "OddsGame1557668323155",
    "machineCode": "300000035000000020b00000005000000100b000000110600000033160107000000330204060000001a7c0200",
    "machineData": "",
    "balanceNQT": "589548670000",
    "prevBalanceNQT": "589548670000",
    "nextBlock": 76258,
    "frozen": true,
    "running": false,
    "stopped": false,
    "finished": true,
    "dead": false,
    "minActivation": "1000000000",
    "creationBlock": 57588,
    "requestProcessingTime": 2
}

For a start it would be nice to be able to filter on the following attributes :

- creatorRS,
- atVersion
- Name
- machineCode,
- creationBlock

Request : Please introduce a new call in BRS which allows to request for a filtered list of ATs.

OpenPoint
Do we need new indexe on the DB for that ?

**Comment by jjos2372** [comment]
Filtering by creator is already available by getAccountATs. However, filtering by name, creationBlock (after some given block) is very desirable. Filtering by machineCode is probably more complicated since the code can be long.

**Comment by ohager** [comment]
Additionally, I suggest to add pagination also.

**Comment by jjos2372** [comment]
Another interesting feature on this subject would be to retrieve the AT machineData for a given block in the past and not only its current state. This way we easily can reconstruct the contract history.

**Comment by ohager** [comment]
@jjos2372 sounds like something we/me want to address soon ;)

**Comment by frankTheTank72** [comment]
We should introduce a new entry on the table for a hash value of the maschine code. Every node is hasing it by it self.
Via BRS you can get all smart contracts wiht the same hash, which makes it easy for NFTs for example

**Comment by jjos2372** [comment]
Filtering by machine code hash id is now available.
