### ISSUE TITLE
Fee suggestion in asset exchange 

### ISSUE THREAD

**Issue by llybin** [signum-network/signum-node#155]
1 Burst now by default

![image](https://user-images.githubusercontent.com/5445357/58814069-47ffde00-864f-11e9-926a-cd99d66286b7.png)

**Comment by llybin** [comment]
Also in Order Cancellation 0.1 Burst by default

**Comment by radogerek** [comment]
1 BURST by default is great IMO

**Comment by frankTheTank72** [comment]
my proposal :   show the fee suggestion from cheap to prio

**Comment by jjos2372** [comment]
Classic wallet is EOL.
