### ISSUE TITLE
I can't decrypt "Encrypttoself message" in transaction

### ISSUE THREAD

**Issue by llybin** [signum-network/signum-node#203]
Version: 2.4.1
No any error in browser console.

![image](https://user-images.githubusercontent.com/5445357/61713417-b412de80-ad82-11e9-916d-0f2945375a63.png)

How to reproduce:
1. Send transaction with filled "Note to Self"
2. After first block confirmation click on transaction and enter passphrase and get error above.
![image](https://user-images.githubusercontent.com/5445357/61713526-0522d280-ad83-11e9-9e4a-3a7f07d03ad0.png)

**Comment by llybin** [comment]
with Arbitrary Message reproduced also

**Comment by deleterium** [comment]
Fixed at https://github.com/signum-network/signum-classic-wallet/commit/d1a8cdff2a1d79dec14dc063bd59814a6aa8ee6f

![image](https://user-images.githubusercontent.com/54009773/193434664-e5615135-10a5-4a20-8139-ff4a46a25cfb.png)

I consider it closed.

**Comment by frankTheTank72** [comment]
closed the ticket as fix provided
