### ISSUE TITLE
Docker disable log file in container

### ISSUE THREAD

**Issue by llybin** [signum-network/signum-node#327]

**Comment by harry1453** [comment]
Do you think it should be outright disabled, moved to a volume, ...?

**Comment by damccull** [comment]
Any container admin can move the file to a volume already by simply mounting the file itself or the folder containing it to a volume, or even binding it to the local filesystem.

However, if it doesn't already exist, the option to specify a log file location would be nice.

**Comment by frankTheTank72** [comment]
outdated
