### ISSUE TITLE
Add transaction timestamp to Subscription output 

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#370]
Currently, the `getSubscription` call returns this:

```json
{
	"id": "11351503202575283428",
	"sender": "6502115112683865257",
	"senderRS": "BURST-K37B-9V85-FB95-793HN",
	"recipient": "11089308770178933578",
	"recipientRS": "BURST-9AUC-LCKL-7W2D-B5BTM",
	"amountNQT": "100000000",
	"frequency": 3600,
	"timeNext": 176579549,
	"requestProcessingTime": 1
}
```

Would be useful to know when the subscription aka tx was created without having to request for the originating tx. So, just adding the `timestamp` and eventually `blockTimestamp` would be fine.

**Comment by th1nkNXT** [comment]
If i had some more information about the concept / data model maybe i could support here. 
My current idea:
We could expand brs.services.impl.SubscriptionServiceImpl.getSubscription(Long) to read the additional data out of the transaction entity. But that is not a good idea as it is used in different contexts. I think we need to provide an own service for the API with an own DTOs as it is more than just a 1:1 transfer of the database entity.

@harry1453 @jjos2372 @ohager 
what do you think?
Some thoughts in general: Normally i work with Spring, Jackson, Hibernate, Lombok, .... Are there any plans to use some of those? At least Lombok could help to avoid writing some boilerplate code.

**Comment by jjos2372** [comment]
> If i had some more information about the concept / data model maybe i could support here.
> My current idea:
> We could expand brs.services.impl.SubscriptionServiceImpl.getSubscription(Long) to read the additional data out of the transaction entity. But that is not a good idea as it is used in different contexts. I think we need to provide an own service for the API with an own DTOs as it is more than just a 1:1 transfer of the database entity.
> 
> @harry1453 @jjos2372 @ohager
> what do you think?
> Some thoughts in general: Normally i work with Spring, Jackson, Hibernate, Lombok, .... Are there any plans to use some of those? At least Lombok could help to avoid writing some boilerplate code.

Hello, I would also have to check the model to implement this. So please fell free to git it a try, PRs are always very welcome.

About the boilerplate code, yes, there is a lot. Using something else would help, again another hand would be nice.

**Comment by th1nkNXT** [comment]
Yes, ok. I will create a PR on that. Think it will take some days. 
I will use v3.0 as base branch in my fork. If that is not ok please give me a message. Commits will be signed.

According to the contributing guidelines i should start on branch develop but i think this is not correct anymore. When do you plan to update develop with the current dev state? Furthermore master seems also to be out of sync. If you need more help just give me a message. I will start with this task to get more familiar with the code.

**Comment by th1nkNXT** [comment]
@jjos2372 
Hi there. Hope you are doing well.

I am nearly finished with a solution and tried to improve the code avoiding to break existing functionality or doing a large refactoring. 

Some questions / remarks:
1. Can i assume that there is always a transaction (or unconfirmed transaction) existing (transactionId = subscriptionId) or do i need to handle the case of a non-existing transaction for a subscription (just to be sure)?
2. I will implement the additional tx information only for the mentioned endpoint `getSubscription`.
3. I introduced a new AccountDto class which is delivered in the JSON data as a future improvement of the data format and code.
4. I wrote a test to ensure that the JSON data is correctly created (and still backward compatible).
5. I added Lombok to the maven pom to reduce boilerplate code. That means when integrating my changes you and other devs need to install the Lombok plugin into your IDE. You should then have a look at my code, maybe there are some things to use for future developments.

**Comment by jjos2372** [comment]
*timestamp* of the original transaction added as requested
