### ISSUE TITLE
Indices for getAccountBlocks doesn't work

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#477]
Calling getAccoutnBlocks and getAccountBlocksId do not respect first and last index args... always all blocks per account returned

https://testnetwallet.burstcoin.ro/burst?requestType=getAccountBlocks&account=BURST-9LSF-V4WN-34E8-4WCMR%20&firstIndex=1&lastIndex=10

**Comment by jjos2372** [comment]
Exactly this had to be kept this way, otherwise the classic wallet will show incorrect numbers. We would need to fix both at the same time.

**Comment by ohager** [comment]
gotcha... maybe removing the index args, would do the trick. It's low prio, but can be misleading!

**Comment by jjos2372** [comment]
OK, added back the indices implementation on develop since the classic wallet is EOL anyway.
ae7b902071233c2c859dd09a0a31fc4d3b1c1130
