### ISSUE TITLE
Burstcoin Classic Wallet has a few transaction sorting categories missing and no next page when you get to the bottom on the Transactions page.

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#491]
Burstcoin Classic Wallet has a few transaction sorting categories missing and no next page when you get to the bottom on the Transactions page.

![Screenshot_20210516-083717_TeamViewer](https://user-images.githubusercontent.com/801414/118403168-fffed980-b621-11eb-8525-6b1379174d7f.jpg)
Missing transaction sorting items in dropdown:
* "Multi-out payment"
* "Add Commitment"

**Comment by shefass** [comment]
It is classic user interface, we are focusing more to Phoenix UI. So in
future probably classic UI will be hidden or becomes optional. So updating
classic UI has very low priority.
sure if someone want to maintain it, it will be updated

2021-05-16, sk, 18:39 Paulpoco ***@***.***> rašė:

**Comment by ohager** [comment]
Yeah, the classic wallet is EOL.

**Comment by paulpoco** [comment]
Then please put real dates and times in the Transactions list for Phoenix

**Comment by deleterium** [comment]
Solved at https://github.com/signum-network/signum-classic-wallet/commit/a29234578e27b351ddb61776df2714f897e405ba

![image](https://user-images.githubusercontent.com/54009773/193433215-0d5fccf8-1fa0-425f-be05-c71b5f609e7d.png)


I consider it closed.

**Comment by frankTheTank72** [comment]
I close as th next update of classic wallet will introduce the missing tx
