### ISSUE TITLE
New docker images for version 3.0.0?

### ISSUE THREAD

**Issue by radanskoric** [signum-network/signum-node#493]
Hi, a few months ago I set up a full node running in my NAS running in docker. I used the latest mariadb based image from [the docker registry](https://registry.hub.docker.com/r/burstappsteam/burstcoin). 

However the latest version there is 2.5.1 from about a year ago so with the recent hard fork it stopped working. 

Are there any plans to publish a new image on the official docker registry? 

P.S. Even better would be to have this done automatically on every release. I'm familiar with Docker basics so if you point me in the right direction I'd be happy to help with a PR to make this a reality.

**Comment by ohager** [comment]
This is definitely something that is on our road map. I really like to see automatic image deploys per GH Actions. Help is really appreciated. I have some basic to intermediate docker knowledge, and I can also deal with GH Actions. Maybe we can start working on something together

**Comment by radanskoric** [comment]
Alright then, when I have some time I'll try and create a PR. I'm not sure when but I hope I'll find the time in the next few weeks.

I'll definitely need help testing it and someone from the project will need to setup secrets when it's ready but I can get it started. I've setup github actions on other project before and I don't think it'll be hard. My plan is basically to follow the github guide, a basic setup will probably be enough: https://docs.github.com/en/actions/guides/publishing-docker-images

**Comment by damccull** [comment]
I maintain a personal docker image that I update regularly. I'll look at this as well when I get some time. I'm just starting with docker actions and I would like to see if I can set up an auto-build for the images.

**Comment by damccull** [comment]
This can probably be closed now. Docker images should start showing up soon.

**Comment by jjos2372** [comment]
Closing as this will be available automatically.

**Comment by TheTimeWalker** [comment]
It doesn't look like it's happening yet. There are no releases on signumnetwork/node in Docker Hub and looking at Github Actions, "Publish Docker image" never gets run

**Comment by ohager** [comment]
We need to reopen this. I think we need to configure the pipelines correctly. Hadn't the time to look into this yet.

**Comment by damccull** [comment]
The current actions file will release it to docker hub when a new release tag is created in the repo. As no new release has been done, nothing has been dockerized. I'll look into making a manual release method possible too.

**Comment by ohager** [comment]
> The current actions file will release it to docker hub when a new release tag is created in the repo. As no new release has been done, nothing has been dockerized. I'll look into making a manual release method possible too.

Let's keep this open until the first release provides a new image in docker hub.

**Comment by TheTimeWalker** [comment]
I can confirm that Docker Hub now has the v3.2.1 published with both h2 and mariadb: https://hub.docker.com/r/signumnetwork/node/tags?page=1&ordering=last_updated
