### ISSUE TITLE
"Incorrect "deadline" param not known" when solo mining with passphrase on node

### ISSUE THREAD

**Issue by singler** [signum-network/signum-node#501]
Hello,
When solo mining with passphrase specified in the BRS node config miner fails to submit deadline. Node returns error
```
	code: 0
	message: {"errorCode":4,"errorDescription":"Incorrect \"deadline\"param not known"}
```
specifying `API.AcceptSurplusParams = yes` allows this configuration to mine successfully.

This issue does not occur when mining with passphrase in miner config.

**Comment by jjos2372** [comment]
Hello, for completeness, please also provide the miner/version you are using.

**Comment by singler** [comment]
signum-miner 1.8.0

**Comment by jjos2372** [comment]
Thank you. We can add `deadline` as an optional parameter just for convenience and simply disregard it.
