### ISSUE TITLE
Classic Wallet in 3.1.0 complains about Reed Solomon address different than Blockchain

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#504]
Classic Wallet in 3.1.0 complains about Reed Solomon address different than Blockchain.  Switch back to Node 3.0.1 
![image](https://user-images.githubusercontent.com/801414/122135634-bc041d80-cdf5-11eb-8733-3795de6b8b2c.png)

**Comment by jjos2372** [comment]
Hello, when you see this message on creating a new account or what is the action?

**Comment by Viperlock** [comment]
I got this message personally after updating from BRS 3.0.1 to BRS 3.1.0.  As soon as you go back into your wallet after updating you get this message.  I'm guessing it has to do with having an existing RS for BURST- prior to updating to the new BRS 3.1.0

**Comment by paulpoco** [comment]
> Hello, when you see this message on creating a new account or what is the action?

When importing existing account

**Comment by th1nkNXT** [comment]
Hi @jjos2372 
I could reproduce a problem after the update to 3.1.0. The sidebar didn't show my address anymore.
I found a change which could be related to this change (sidebar.html):
```
Revision: f0f722554a7f04e1d84a94e4700d0e132636b5ef
Date: 27.03.2021 23:07:23
```
After restoring the old code, the address is shown again:
```
        <div id="account_id_dropdown" class="dropdown">
          <span id="account_id" class="dropdown-toggle" data-toggle="dropdown" data-type="account_id"></span>
          <ul class="sbdropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="account_rs" data-i18n="copy_account_id">Copy Account ID</a></li>
            <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="account_id">Copy Numeric Account     ID</a></li>
            <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="message_link" data-i18n="copy_send_message_link">Copy "Send Message" Link</a></li>
            <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="send_link" data-i18n="copy_send_burst_link">Copy "Send BURST" Link</a></li>
          </ul>
        </div>
```
![image](https://user-images.githubusercontent.com/18901038/122472496-f7067c80-cfc0-11eb-9858-fa18577ad988.png)

I do not now if this can also have an affect of the mentioned problem here but maybe it helps.

**Comment by jjos2372** [comment]
> Hi @jjos2372
> I could reproduce a problem after the update to 3.1.0. The sidebar didn't show my address anymore.
> I found a change which could be related to this change (sidebar.html):
> 
> ```
> Revision: f0f722554a7f04e1d84a94e4700d0e132636b5ef
> Date: 27.03.2021 23:07:23
> ```
> 
> After restoring the old code, the address is shown again:
> 
> ```
>         <div id="account_id_dropdown" class="dropdown">
>           <span id="account_id" class="dropdown-toggle" data-toggle="dropdown" data-type="account_id"></span>
>           <ul class="sbdropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
>             <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="account_rs" data-i18n="copy_account_id">Copy Account ID</a></li>
>             <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="account_id">Copy Numeric Account     ID</a></li>
>             <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="message_link" data-i18n="copy_send_message_link">Copy "Send Message" Link</a></li>
>             <li role="presentation"><a class="copy_link" role="menuitem" tabindex="-1" href="#" data-type="send_link" data-i18n="copy_send_burst_link">Copy "Send BURST" Link</a></li>
>           </ul>
>         </div>
> ```
> 
> ![image](https://user-images.githubusercontent.com/18901038/122472496-f7067c80-cfc0-11eb-9858-fa18577ad988.png)
> 
> I do not now if this can also have an affect of the mentioned problem here but maybe it helps.

Hello, can you send this in the form of a pull request please?
(the original issue should be solved already now and will be on the next release)

**Comment by th1nkNXT** [comment]
Hi, yes ok. I will create a pull request for #508 to fix the issue i mentioned.

**Comment by damccull** [comment]
What was the solution for original issue, @jjos2372? Would be nice to have documentation on it.

**Comment by paulpoco** [comment]
Fixed awhile ago

**Comment by jjos2372** [comment]
> What was the solution for original issue, @jjos2372? Would be nice to have documentation on it.

Sorry, I missed that. It was just the prefix thing BURST- vs S-.
