### ISSUE TITLE
Limit RAM Consumption under Linux

### ISSUE THREAD

**Issue by Land3r** [signum-network/signum-node#515]
Hello guys,

I rencently tried to setup my first signum node under linux, but i am having issues because of my server.
I have a ton of storage, however i don't have a lot of RAM.

After a first run, i got the following : 

>[INFO] 2021-07-01 01:51:24 brs.statistics.StatisticsManagerImpl - handling 10.00 blocks/s account cache hit ratio now/total:99.44%/98.73%
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e9a00000, 28835840, 0) failed; error='Cannot allocate memory' (errno=12)
> **There is insufficient memory for the Java Runtime Environment to continue.**
> **Native memory allocation (mmap) failed to map 28835840 bytes for committing reserved memory.**
> An error report file with more information is saved as:
> /home/burstpool/hs_err_pid28231.log
>sh-4.4$ java -jar burst.jar

The synchronisation process crashed after a few 1000 blocks.
It the a way to specify a RAM limit through command line ?
What can i do ?

Thanks for help

**Comment by jjos2372** [comment]
Hello, you can try to limit it on the virtual machine level, for instance `-Xmx512m`. Let us know if that helps.

**Comment by Land3r** [comment]
It is working :) (but it is very slow)
`java -Xmx512m  -jar burst.jar`

At the current rate, it should take me around 10 days to sync with the network

**Comment by damccull** [comment]
As long as you use the same db format (h2 or mariadb), you can transfer a copy from another machine, yes.

**Comment by jjos2372** [comment]
Yes, in that case you better bootstrap the DB from another machine (for H2, which is the default, you just copy the DB folder with the node not running). There is also a API to create a ZIP for the H2 database with the node hot (check the configuration file for the details). People do that to have a fast sync node using even a Raspberry Pi 3 or 4.

**Comment by jjos2372** [comment]
BTW you can check the API on any node at https://europe.signum.network/api-doc

**Comment by Land3r** [comment]
Node is now running :)
Thanks for the help.

I am closing the ticket as the original issue was answered.
