### ISSUE TITLE
Is Name length too long at 100 characters?   It messes up the Signum Pool web display.

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#522]
Is Name length too long at 100 characters?   It messes up the Signum Pool web display.  I thought seeing an S- Address was long but this one is really long.
![image](https://user-images.githubusercontent.com/801414/124635606-7955c400-de3c-11eb-9d18-bb3debb7e94f.png)

https://github.com/signum-network/signum-node/blob/b7568a79a0ab7079cc4f9353c60a106765987ef7/src/brs/Constants.java#L47

Maybe no longer than an S- address 22 characters or 26 for backwards compatibility with BURST-

**Comment by jjos2372** [comment]
Thanks for reporting, we will limit this to less characters on the pool.

**Comment by jjos2372** [comment]
This is fixed on recent pool software, limiting their length there.
