### ISSUE TITLE
Host Signum databases in a Github repository

### ISSUE THREAD

**Issue by shefass** [signum-network/signum-node#528]
Now [MAX_ROLLBACK](https://github.com/signum-network/signum-node/blob/c919416e7613538bcd71e5c283ca5544bb132d5e/src/brs/Constants.java#L36) is 1440 blocks. It is (1440 x 4 minutes) / 60 / 24 = 4 days.  All what happened before 1440 blocks can be considered as true and cannot be changed without hard fork. Now we have block height [910372](https://explorer.signum.network/) and it is about [5 GB](https://explorer.signum.network/?action=network_chart&submenu=blockchainsize) of data, so to sync a Signum Node you need that other nodes send it. It rises "price" of running node.

I propose:
1) Host a one week old H2 database at signum-network organization new repository signum-blockchain and update it weekly. This will create opportunity to quickly sync nodes. 
2) Create options in a Signum Node configuration file: DB.bootstrap = yes; and DB.bootstrap_url = https://github.com/signum-network/signum-blockchain/.. (I hope my idea is obvious and it is just guideline for implementation) 

I think DB.bootstrap can be by default yes. It will save a lot of traffic and time.

**Comment by Nivok-Spilkommen** [comment]
I agree with this in principle but not sure if github is the right place to host it.

**Comment by shefass** [comment]
I think it is best place to host, because we will not create new "weak" point for Signum Network. If we trust signum-network organization at the github, we will trust its repositories.

**Comment by dompie** [comment]
I would vote for a new config option that will - when enabled - expose a sql dump for download on the node, together with a checksum file.
This way you do not have to trust a single point (of failure), can mitigate attacks on single points of truth and everybody who needs a dump can choose his own, trustworthy node to download the dump from.

Making the config option ... optional will give node-operators the power to decide on their own, if they want possible extra traffic/load cost or not.

**Comment by Zoh63392187** [comment]
It's not the true blockchain spirit to host any dump anywhere as it could have been altered.

**Comment by damccull** [comment]
I'm with @Zoh63392187. Official db dumps should not be a thing. The blocks do not get verified properly in a dump download like this. If this does become a thing, the client needs to be modified to do a full check on the db if a dump is installed.

**Comment by gittrekt** [comment]
> We have a Dump Option already implemented on the node:
> 
> ![image](https://user-images.githubusercontent.com/3920663/139048622-6002f1a4-7e8c-4637-9ea6-e02d5a890863.png)
> 
> I think we can close this issue. Wdyt? @damccull @shefass @Zoh63392187 @dompie

Accessing that isn't obvious to the average user who might just want a simple migration from one server to another, and not fully understand the api though.

**Comment by damccull** [comment]
A simple migration to another server just needs the user to copy their own existing database over to it. H2 is stored right in the app directory structure so there's no reason for a dump here.

Dumps can be dangerous to the chain as discussed in previous comments. But I've been happy to provide dumps to others in the past when asked and I know others will do it too.

I vote to close this since a dump function already exists, those who want a dump can likely ask for one and get it, and the chain is more robust when synchronized natively.
