### ISSUE TITLE
phoenix-update.sh URL needs to be fixed

### ISSUE THREAD

**Issue by toconspiracy** [signum-network/signum-node#532]
https://github.com/signum-network/signum-node/blob/1cb86911b6427a903c7633318ea572171e45acd8/docker-scripts/update-phoenix.sh#L18

The Script is broken because of a defunctioning Path (Think because of renaming). Issue is:

`curl -s "https://api.github.com/repos/burst-apps-team/phoenix/releases/latest"
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/164716981/releases/latest",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"`

Results in this during a Dockerstart:

🛰 Updating Phoenix Wallet to current release...
⬇️ Downloading latest release...
📦 Extracting files...
unzip:  cannot find or open web-phoenix-signum-wallet.*.zip, web-phoenix-signum-wallet.*.zip.zip or web-phoenix-signum-wallet.*.zip.ZIP.

Either the new URL need to be added (which i think is https://api.github.com/repos/signum-network/phoenix/releases/latest) or we need to change it to the referenced one: https://api.github.com/repositories/164716981/releases/latest

**Comment by ohager** [comment]
done
