### ISSUE TITLE
Locked commitment that shouldn't be locked

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#547]
Last got a block 2 days and 3 hours ago.

Added 1200 commitment about 4hrs ago.

About 30 minutes ago tried to remove 100 commitment and it said not allowed.

Shouldn't I be able to remove commitment that was added after a block was won?

Of course just got a block now so kind of moot now.

**Comment by jjos2372** [comment]
> Last got a block 2 days and 3 hours ago.

So all is locked for the next 4 days, regardless if they are new additions or added long back.

**Comment by paulpoco** [comment]
Thanks
