### ISSUE TITLE
AT: Issue handling multi-out transactions

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-node#552]
What happens:
Sending a transaction via multi-out payment to smart contract cause them to activate (if amount is bigger than activation amount), but the API `A_To_Tx_After_Timestamp` does not find that multi-out transaction. If multi-out is the first transaction sent to contract, API returns error (-1).

**Comment by jjos2372** [comment]
A multi-out does not have an "explicit" receiver and the amount received by an specific address is not directly available on the transaction body (only in the attachment). So, unless there is a strong argument here, I would keep it this way.

**Comment by deleterium** [comment]
Just remember that the api `A_To_Tx_After_Timestamp` returns error in this case, if it does not find any transaction at all. I would just change this case so the return value is zero.

In a regular use, the program can think that the -1 value is a transaction id, and tries to get values from this transactions, getting more errors in other values.

**Comment by jjos2372** [comment]
Thanks, we need to find where this is taking place. Because according to this it would return 0L:
https://github.com/signum-network/signum-node/blob/d4ea01c42288385a36332b56c4ce6d6455d6f03e/src/brs/db/sql/SqlATStore.java#L250

**Comment by deleterium** [comment]
You are right, this code already is OK. Probably I got the result of other API with null txid, because I tried to find the code and also did not find.
