### ISSUE TITLE
Add the ability to deploy smart contracts for tokens created on the Signum blockchain in BTDEX

### ISSUE THREAD

**Issue by RoyalRanger** [signum-network/signum-node#554]
Please add the ability to deploy smart contracts for tokens created on the Signum blockchain in BTDEX. Or maybe you can add one SOLD token (id15404947523559533783) to the market for BTDEX? I'm preparing a project https://siju.me / where anyone can advertise the sale and purchase of goods and services for SIGNA, as well as perform tasks remotely, with payment in SIGNA. The user must be able to make transactions through the BT DEX exchange. The SOLD token was created by me, just for the implementation of such transactions.

**Comment by frankTheTank72** [comment]
Via the swap menu everyone can add a token 
![grafik](https://user-images.githubusercontent.com/39116221/136834639-44c20197-fda3-479d-8f4b-eb79eaee399e.png)

So if people like to trade your token they just need the token-id from you

**Comment by jjos2372** [comment]
Not directly related to the node code.
