### ISSUE TITLE
Signum Explorer CSV Beta export gets most addresses wrong

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#560]
Signum Explorer CSV Beta export gets most addresses wrong.  It seems to get your address correct.
![image](https://user-images.githubusercontent.com/801414/137830758-b4b41f1b-ea1f-4828-8913-0b78ad9c5876.png)

Example
S-XKP6-2L56-PNEP-FNYKT "Signum Network Rewards" is S-4GCW-ZFWV-VJYN-4D3G8 on CSV Export (Beta)
S-9XWW-KTBN-3V66-8VV6F "SIGNA.pool.notallmine.net" is S-9XWW-KTBN-3V66-8VV6F on CSV Export (Beta)
S-Y3RT-LCYX-ZZ4F-BMSKR "harvey-bot" is S-3YA9-FP34-SA64-8E9GA on CSV Export (Beta)

The fees are not part of the export.

**Comment by jjos2372** [comment]
Hello, this repository is not for this explorer, please check with @Zoh on the discord server.
