### ISSUE TITLE
Signum-node on Windows closes window before the node is shutting down

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#566]
Symptom:
I find on windows that closing Windows 10 Signum-node with tray icon shutdown function, closes the node window too soon.  You think it is closed but if you have defrag setting to on, the Java is still running defraging.

Expected:
Windows 10 Signum-node shouldn't close until it is completely done closing the DB H2 file.

Possible DB issues: 
Corruption

**Comment by paulpoco** [comment]
No comment or concern from anyone else?

The only way I know it is done shutting down is Task Manager and the OpenJDK is gone.
![image](https://user-images.githubusercontent.com/801414/142778424-4f90479c-b22d-4366-be6d-e5c5d34782ed.png)

**Comment by ipr0310** [comment]
![image](https://user-images.githubusercontent.com/35440957/143873102-2d5346ca-33ea-4c79-b915-d36312bd952f.png)
Yeah, maybe that happen because the node is with the H2 files, shuting down the node using mariadb, goes smooth!

**Comment by paulpoco** [comment]
I guess a proper shutdown of SIGNUM-NODE is not important.

What if someone closes it properly and then starts it up again but the previous closing still is going on?

Should I just close this ticket?  I guess yes.

**Comment by paulpoco** [comment]
Still closes running Window before the Signum-node is done with the DB file. 

Also could have more info in the Log file while shutting down.   Like . . . . increasing dots, then actually saying fully done when finished with DB file.

**Comment by jjos2372** [comment]
Fixed on the develop branch.
