### ISSUE TITLE
Missing Multi-Out transactions when calling getAccountTransactions #2

### ISSUE THREAD

**Issue by andzno1** [signum-network/signum-node#569]
I was just testing the fix for #447 when I ran into the following problem.

For account S-GT5F-6VQD-CLM6-6Q5BX the [explorer](https://explorer.signum.network/?action=account&account=5666784140691203181) shows 2124 transactions in total. 22 of them are Multi-Out-Same and 1708 are Multi-Out transactions.

When testing the fix for #447 I noticed that my local wallet returns most of the transactions correctly, but there are still some transactions missing.

When fetching Multi-Out-Same transactions from `https://europe2.signum.network` I am getting 22 transactions (as expected):
```bash
 curl "https://europe2.signum.network/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&subtype=2&type=0&includeIndirect=true" | jq -r '(.transactions) | length'
```

When making the same call to my fully synchronized local wallet (v3.2.1) I am getting only 8 transactions:
```bash
 curl "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&subtype=2&type=0&includeIndirect=true" | jq -r '(.transactions) | length'
```

Further investigation shows that the following Multi-Out-Same transactions are missing:
> 10065574561891767476
> 11692003314071146951
> 5374104613642814665
> 9791677772117405278
> 1829295365588247739
> 16102347849798588205
> 7135089631096934213
> 14622580420469649884
> 9730868509400489479
> 7667547325904032098
> 16684904913720657928
> 5973081839981246218
> 8726120175280690530
> 13182859542118334594

The same happens with the Multi-Out transactions. When fetching from `https://europe2.signum.network` I am getting 1708 transactions in total, when fetching from my local wallet there are 67 transactions missing. This is the relevant call:
```bash
 curl "https://europe2.signum.network/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&subtype=1&type=0&includeIndirect=true&firstIndex=1500&lastIndex=1999" | jq -r '(.transactions) | length'
```
Yields 208 transactions.
```bash
 curl "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&subtype=1&type=0&includeIndirect=true&firstIndex=1500&lastIndex=1999" | jq -r '(.transactions) | length'
```
Yields 141 transactions.

The following Multi-Out transactions are missing:
> 3578439527840352455
> 5294188778046251490
> 585168338105147687
> 3344999936680861602
> 8954631170780609903
> 5205577912207376448
> 1346390278401095332
> 9802041511973137294
> 15228474699159637782
> 16274158926827197063
> 7660352485733848661
> 9891304244866968243
> 7711319385042898061
> 11449690098279827769
> 1457490819272976447
> 1881280439134027928
> 16467261393944107713
> 3845785580529298637
> 14400980216971607748
> 7788169862862598513
> 2929442438760625739
> 3854748751464166332
> 13084184394822289754
> 12557990261299480292
> 12278259455876805222
> 4610904353288357624
> 13117080473754531741
> 9883569977936222895
> 9288092447989045035
> 3994718647706055225
> 5476400344730330120
> 6295041188515250187
> 8364981822915033359
> 2569810908988869307
> 7126038093217529443
> 6060884288854668193
> 17230563979904136229
> 14979771489260527792
> 9362987858085099219
> 14751101560050403593
> 17799078458811186571
> 10225955007060682372
> 1172215276142998939
> 8575833908285827544
> 640267280453138994
> 7284497444946467022
> 5116286647886060787
> 8094643878133704726
> 17288700366783337276
> 5860168704896426780
> 10448198485897712650
> 16641854340877713995
> 637613736822023414
> 4759511958580194511
> 7888697080992808268
> 13960175306898195643
> 6115521916399767936
> 1653443259618881558
> 16025083998659969816
> 1059839195884683167
> 1013601033901354141
> 13239765146955485614
> 8431040442125280510
> 266863763471128189
> 953787980889413749
> 970968183177999908
> 14355294268895986418

I hope that the fix won't be to drop the database and to re-download the blockchain, since I feel that this should work with a fully synchronized node.

**Comment by ohager** [comment]
@jjos2372 is this still relevant?

**Comment by jjos2372** [comment]
I just executed the tests above in two different nodes and they all returned the expected result.
