### ISSUE TITLE
Flyway upgrade recommended with mariadb 10.5

### ISSUE THREAD

**Issue by alicks** [signum-network/signum-node#573]
Testing 3.3.0-alpha1 on debian11 with mariadb, got a warning:

[WARNING] 2021-12-03 20:10:43 org.flywaydb.core.internal.database.base.Database - Flyway upgrade recommended: org.flywaydb.core.internal.database.mysql.mariadb.MariaDBDatabaseType@567c3ead 10.5 is newer than this version of Flyway and support has not been tested. The latest supported version of org.flywaydb.core.internal.database.mysql.mariadb.MariaDBDatabaseType@567c3ead is 10.4.

My mariadb:
Server version: 10.5.12-MariaDB-0+deb11u1 Debian 11

Skip it if it is known.

**Comment by ohager** [comment]
I stumbled over that yesterday also....

For those on Linux (Ubuntu/Debian):

https://mariadb.com/docs/operations/upgrades/upgrade-community-server-cs10-5-ubuntu18/

**Comment by ohager** [comment]
No issues with 3.3.3... @alicks can we close this.

**Comment by alicks** [comment]
Hi. Sure. No more issue with that.
