### ISSUE TITLE
API getTransactionsIds wrong limits

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-node#577]
**Describe the bug**
API getTransactionsIds does not apply limits requested by user.

**To Reproduce**
1. Get all transactions from sender 16625027912348105044:
http://lmsi.club:6876/burst?requestType=getTransactionIds&sender=16625027912348105044

2. Try to apply limits on query, i.e. get from second and following:
http://lmsi.club:6876/burst?requestType=getTransactionIds&sender=16625027912348105044&firstIndex=2

**Expected behavior**
The second query must reply the transactions but not two first: "6573069290654359521", "3737327596417861055".

**Comment by EvolverDE** [comment]
what the api-doc page feels like:
![gettxids_feelslike](https://user-images.githubusercontent.com/30400562/147580340-cdafa5a3-84f5-4676-8db0-ed9627904d2f.jpg)
what it should be:
![gettxids_shouldbe](https://user-images.githubusercontent.com/30400562/147580367-d9752b88-24ac-47c4-91d1-f86775271e3f.jpg)
