### ISSUE TITLE
bug: api getBlocks has no cap on data returned

### ISSUE THREAD

**Issue by rogerwim** [signum-network/signum-node#606]
### bug
The getBlock api can return a very large ammount of data(400+ MB) and can take a long time to respond, this can cause DOS attacks
### suggested fix
Either make the call return a maximum ammount of data or have a maximum number of blocks, you can require a apikey to not have a limit, also some kind of rate limit or timeout could also fix this

**Comment by ohager** [comment]
good catch :clap:

**Comment by rogerwim** [comment]
> good catch 👏

Yea, this is important and should be fixed as soon as practical
