### ISSUE TITLE
getBalance request does not have the option to show Commited Amount

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-node#616]
In ``getBalance`` request, there should be a parameter which gives the option to also show the ``commited amount`` of the account
![image](https://user-images.githubusercontent.com/35440957/172662167-18980687-a31d-4c03-b259-4e5a918f0f88.png)

It already exists in ``getAccount``, but that request also is showing properties that in a certain use-case a developer may not need
![image](https://user-images.githubusercontent.com/35440957/172662743-4f9c851a-05ec-4b53-b51f-10a1ebc240a8.png)

The benefits of adding the parameter ``getCommittedAmount`` in the ``getBalance`` request may be the following:
- Less node resources usage because of possible use-cases where developers just need the available and commited balance of a account

**Comment by jjos2372** [comment]
`getBalance` already returns `unconfirmedBalanceNQT` which is what is available to be moved by the user (meaning you already have what is available).

Please close the issue if that solves the problem.

**Comment by ipr0310** [comment]
Yes, is confirmed. Thanks!
