### ISSUE TITLE
New API call to support distributeToAssetHolders

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#618]
We should have a new API call which returns only the number of token holders by the given input paramters from [distributeToAssetHolders](https://europe1.signum.network/api-doc?requestTag=AE#).

The call should be named **getDistributeToAssetHoldersNumber**

**Comment by ohager** [comment]
Context: this helps on the upfront fee calculation, which is 0.001 * numberOfEligibleHolders

**Comment by frankTheTank72** [comment]
This is covered by the getAsset function - handing over the quantityMinimumQNT.
And in the result we will get ´numberOfAccounts´
