### ISSUE TITLE
Circulation via API call is not correct (minus 1)

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#621]
Following the new TMG Game where the smart token is minted via SC, the number of the circualtion quantity is not shown correct on the explorer : https://chain.signum.network/asset/11955007191311588286

Also the direct API call on the Node **getAsset** is not correct ( minus 1):

`{
    "account": "18339269626061634110",
    "accountRS": "S-9GKY-KWQS-HTZG-HEK2X",
    "name": "TMG",
    "description": "Token issued and controlled by smart contract ID: 18339269626061634110",
    "decimals": 2,
    "mintable": true,
    "quantityQNT": "0",
    "quantityCirculatingQNT": "5600",
    "asset": "11955007191311588286",
    "numberOfTrades": 0,
    "numberOfTransfers": 59,
    "numberOfAccounts": 12,
    "requestProcessingTime": 26
}`

In this example it shows 56 but the holdings are 57 and this can be confiremd by a DB check :

`SELECT SUM(quantity) FROM account_asset WHERE asset_id = -6491736882397963330 AND latest = 1`

As the minting is done on a hourly base  this may help as a hint what is wrong in the API code.

Solution:
The API Call and DB state should be in sync.

**Comment by ohager** [comment]
@jjos2372 Is that being fixed with #638?

**Comment by jjos2372** [comment]
@frankTheTank72 we have to check if the latest improvements have already this correct.

**Comment by frankTheTank72** [comment]
Yes look good - close the ticket
