### ISSUE TITLE
Committed Balance isn't updating, and it differs from Locked Balance in BTDEX and in chain.signum.network

### ISSUE THREAD

**Issue by atomsymbol** [signum-network/signum-node#624]
**Major issue:** The value of "Committed Balance" isn't updated after a transaction of type "Add Commitment" is confirmed.

----

Minor issue (but still an issue): The "Committed Balance" displayed by http://....:8125/classic.html and by https://signapool.notallmine.net differs from "Locked Balance" displayed by BTDEX and by https://chain.signum.network

----

signum-node v3.4.2

btdex v0.6.3

![Screenshot_20220721_210003](https://user-images.githubusercontent.com/22368256/180295779-551ff1dc-8687-4496-81b9-8cf4076aa8a4.png)

----

https://chain.signum.network/address/...: Locked Balance = 3862 SIGNA

https://signapool.notallmine.net is displaying a commitment of 3834 SIGNA.

**Comment by jjos2372** [comment]
That is because the amount is locked but only *effective* as commitment 4 days later. After that period of time, they should match.

**Comment by atomsymbol** [comment]
Ok. Where is this behavior/fact documented?

**Comment by frankTheTank72** [comment]
> 

here --> https://github.com/signum-network/SIPs/blob/master/SIP/sip-32.md

**Comment by atomsymbol** [comment]
Thanks.
