### ISSUE TITLE
Add trading price/volume to  API responses

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#627]
For the upcoming DeFi portal the trading volume over a period, e.g. 24h, is needed. As this is a general KPI for tokens, we should add such a field to the Token  API. Ideally, the parameter is variable, such one can determine different time periods.

Suggestion for the parameter:

`tradingPeriod` with value in minutes
`showTokenWithZeroVolume` is default 'False'

Affected API calls:

- `getAllAssets`
-  `getAsset`

It shows all metadata from the token and the below values in the comment

**Comment by frankTheTank72** [comment]
I think this is like #631  an addtion to the getAsset call.

We should have by default tradingVolumePeriod for 24hrs aka 1440 minutes.
The valume should be calcuated by all executed trades within this time period.
We could also intriduces the follwoing calculated values :

- Last Price
- Last Price Timestamp
- LatPrice Quantity
-

**Comment by frankTheTank72** [comment]
@jjos2372 
'getAllAssets' seems not  adjusted on the API ?
![grafik](https://user-images.githubusercontent.com/39116221/188713424-cf28c0d9-03a3-47cb-aabf-7546129e8272.png)

tradingPeriod with value in minutes and  showTokenWithZeroVolume is default 'False' is missing

**Comment by jjos2372** [comment]
`showTokenWithZeroVolume` have to be default `true` or it will break existing code.

**Comment by jjos2372** [comment]
To avoid the *token* vs. *asset*, I'm suggesting to have an option `skipZeroVolume` instead. The default would be `false` to avoid breaking existing code. This would apply to `getAssetsByIssuer` and `getAllAssets`.
