### ISSUE TITLE
Make it possible to see burnt and minted quantity of an asset

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#631]
It should be _easily_ possible to see the burnt and minted quantity of a token.

**Comment by frankTheTank72** [comment]
You mean here ? 
![grafik](https://user-images.githubusercontent.com/39116221/181933981-6543f9eb-fcb1-4670-be02-fca9af570ee7.png)

Like:
NumberOfMints
QuantityMinted
NumberOfBurns
QuantityBurned

**Comment by ohager** [comment]
yeah... prolly, the best place to put.

**Comment by frankTheTank72** [comment]
quantityBurntQNT is added 

Still missing:
NumberOfMints
quantityMintedNQT
NumberOfBurns
