### ISSUE TITLE
DistributionToHolder tx adjustment (sell-orders)

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#642]
**Issue**
Currently, the DistributionToHolder works technically very well. 
One small problem is that the current sell orders on the smart token on which the distribution is based are not included in the calculation. So if a user has an active sell order in that smart token on the on-chain market, those positions are not included in the distribution.

**Solution**
We should include the active sell orders in the calculation/position for an account and pay based on that total.
To get the sell orders back into the distribution, we need to remove the sender of the tx from the calculation and include the token's unconfirmed balances from all other accounts again.

The circulating quantity must be adjusted for a possible sender position in the smart token on which the distribution is based.

**Comment by deleterium** [comment]
My feedback is that circulation supply for smart contract must include the quantities in sell orders and currently in account. A case that I thought and it is not currently possible is the following:
The current WheelOfSigna burns some amount configured by owner. My idea is that the burn quantity is adjusted by current circulating supply (i.e. keep no more than 20% in account). Currently it is not possible, because if some bad actor put the token on sale, the calculation will disregard this amount and a bigger value will be burnt. The bad actor removes the sell order and then suddenly the contract has, let say only 10% of circulating supply.

**Comment by jjos2372** [comment]
Yes, we should account all tokens as shares (including those in sell offers). But then we cannot include the tokens that the account making the distribution holds. That is the proposed solution. Also open to other suggestions on how to handle the case when you distribute a token which you also hold.

**Comment by frankTheTank72** [comment]
> My feedback is that circulation supply for smart contract must include the quantities in sell orders and currently in account. A case that I thought and it is not currently possible is the following: The current WheelOfSigna burns some amount configured by owner. My idea is that the burn quantity is adjusted by current circulating supply (i.e. keep no more than 20% in account). Currently it is not possible, because if some bad actor put the token on sale, the calculation will disregard this amount and a bigger value will be burnt. The bad actor removes the sell order and then suddenly the contract has, let say only 10% of circulating supply.

@deleterium the circulation supply is only adjsuted for the distributionToHolders tx  to solve the problem as stated and commented from @jjos2372. Circulation supply in itself includes all amounts plus sell orders. This has also already been introduced with the last test node (3.4.3).

Is that helpful ?

**Comment by deleterium** [comment]
@frankTheTank72 Maybe we have another issue, because for smart contract I did a test now and it did not included the sell order. I'll give more details in discord to @jjos2372

**Comment by frankTheTank72** [comment]
@deleterium the fix is not active on testnet right now - maybe we have on the upcoming weekend a new release including the adjustments

**Comment by frankTheTank72** [comment]
@jjos2372  While testing can we avoid adding indirect_income entries for accounts which are not getting any Signa or token - so amount/quantity is = zero
![grafik](https://user-images.githubusercontent.com/39116221/184480173-a71f3ef9-8751-4808-b84c-9473ecebd928.png)

and here the DB entry :

![grafik](https://user-images.githubusercontent.com/39116221/184480220-f7c744be-c0ef-4055-99f4-a41df7cdc6cc.png)

Only as example as this is on **testnet2** which may disappear soon

**Comment by jjos2372** [comment]
From past experience I would say it is better to keep it this way, and not having to investigate "why my account was not included in the distribution?" over and over again.

**Comment by frankTheTank72** [comment]
> From past experience I would say it is better to keep it this way, and not having to investigate "why my account was not included in the distribution?" over and over again.

Or we print the condition as minimum quantity on the explorer to be valid

**Comment by frankTheTank72** [comment]
Fixed with release 3.5.0
