### ISSUE TITLE
Ticket for API feedback

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#644]
Adding per comment calls which seems not correct

**Comment by frankTheTank72** [comment]
![grafik](https://user-images.githubusercontent.com/39116221/184475154-dcc90f94-a30f-45f1-bed1-63e4c0b5b231.png)

should be account not asset

**Comment by ohager** [comment]
![image](https://user-images.githubusercontent.com/3920663/184622237-91046ea7-f92b-463f-a9f6-0149a8291cac.png)
