### ISSUE TITLE
priceNQT in Trade Responses and Order Methods are not expressed in Planck

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#654]
The following API methods work with a parameter called `priceNQT:

- getAssetTrades
- getAllTrades
- getAskOrder
- getAskOrders
- getBidOrder
- getBidOrders
- placeAskOrder
- placeBidOrder

The problem is that the field name `priceNQT` indicates the use of a Signa price expressed in Planck, but actually it's expressed 
in a kind of value which depends also on the decimals of the related token. 

The problem is, that the API is not only inconsistent, but also provokes wrong values, which can finally damage developers/business. A developer expects to send Plancks and not something like `planck / (10 ^ decimals)` or expects to get plancks and not something like `planck / 10 ^ (8 - decimals)`

**Comment by ohager** [comment]
I understand that this impacts platforms like BTDEX, but it's best to solve this as early as possible, because with a grown up eco-system, this issue will/can cause a lot of trouble

**Comment by frankTheTank72** [comment]
@jjos2372 i am supporting this proposal - we should show the price in Planck - means adding the zero by decimals onto the stored price.

**Comment by frankTheTank72** [comment]
Also for 'placeBidOrder' and 'placeAskOrder' we should have Planck as priceNQT. The API should check and convert the entry into the needed "internal" format ... if  it results in a Zero price we reject the entry

**Comment by frankTheTank72** [comment]
Oh just saw that @ohager already mentioned the placeorders :-)

**Comment by deleterium** [comment]
I would use the name "priceNQTbyQNT" to be clear, because the representation of the value is how much NQT costs one QNT in that order.

**Comment by jjos2372** [comment]
In order to keep all existing code working, we need to keep the current fields and add new ones with the desired value. Something  as @deleterium suggested.

**Comment by frankTheTank72** [comment]
Okay so let us go for `priceOfOneQNT` - this is clearly described and also readable for someone with no experience in equity trading. 👍 

I adjust the other tickets

**Comment by frankTheTank72** [comment]
@ohager later we should just remove in the API the `piceNQT` from the documentation

**Comment by frankTheTank72** [comment]
finally we introduced `price` as new field

The following transactrions are not adjsuted right now :

- placeAskOrder
- placeBidOrder

**Comment by jjos2372** [comment]
> finally we introduced `price` as new field
> 
> The following transactrions are not adjsuted right now :
> 
> * placeAskOrder
> * placeBidOrder

The `price` property was added as an output for some requests. I don't think we should add it on the place ask/bid requests, as they need to be converted internally (and not necessarily exactly - as per the number of decimal places available for the price).

**Comment by frankTheTank72** [comment]
okay so let it close and make a new one if needed for the place-txs.
