### ISSUE TITLE
New API call getTradeJournal

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#658]
Currently we have single API calls to request orders or trades for account(s) and token(s). 
This is technical okay, but those calls are not fitting into the nedd for a DeFi portal.

To handle the requirement we propose to create a new API call : `getTradeJournal`
Parameter to enter :
- Account-ID
- Token-ID

The call is always for a given account + token.

The JSON output looks like this:

`
{
account: "ID",
token:"ID",
tradeJournal:
  [
   order-id:"tx-id",
   timestamp:"tx-timestamp",
   status: integer,
   tradeType:"buy or sell"
   limitNQT: "limit from tx",
   quantityQNT:"quantity from tx",
   averagePriceOfOneQNT: float,
   executedAmountQNT:float,
   executionSlides:
      [
        trade-id:"trade-id",
        timestamp:"trade-tx",
        height:integer,
        quantityQNT:"quantity from trade",
        priceOfOneQNT:"price from trade"
       ],
      ]
      }
`

**Description**

- account: The account from the request
- token: The token from the request
- `tradeJournal`: The section with the list of open/closed and canceled orders for the given account/token
  - order-id: The ID from the transaction which creates the buy or sell order
  - timestamp: The timestamp from the transaction which creates the buy or sell order
  - status : A integer value with the following range:
    -  (-1) order is caneled
    - (0) order is open
    - (1 until 99) partial fill ofd the order in %
    - (100) order is closed ( 100% filled)
  - tradeType: Direction of the order (buy/sell)
  - limitNQT: The limit set on the transaction in Planck ( converted)
  - quantityQNT: The amount of tokens to buy or sell from the original transaction
  - averagePriceOfOneQNT : The calcualted execution price by all `executionSlides`
  - executedAmountQNT: The sum of all amount by the `executionSlides`
  - `trades` : In this section we show all trades related to the order-id
    - trade-id : ID of the trade
    - timestamp: Timestamp of the trade
    - height : Block-ID
    - quantityQNT : Executed amount
    - priceOfOneQNT: Excecuted price for the quantityQNT 

**Logic**

We should loop over all transaction from the account for Place BID/ASK orders filtered by asset(token)
In this case we have the main list of all orders from the user.
Now we loop over all trades by the order-ids. We filter on asset-id (token) and check ask_order_id/bid_order_id.
Finally we check all Cancel transaction and set those order-ids to status -1

The NQT fields should be expressed in Planck ( see #654 )

This ticket covers the following requirements:

- #657 
- #656 
- #655

**Comment by jjos2372** [comment]
I believe we do not have `float` values in any other end point. So I suggest we replace `averagePriceOfOneQNT: float` and `executedAmountQNT:float` by having the `executedAmountQNT` and `executedVolumeNQT`, the second one is in SIGNA NQT, so the average price can be calculated.

**Comment by frankTheTank72** [comment]
hi @jjos2372 i think to use the same pattern your proposal is good - the price can be calculated from those two values as you described.

**Comment by jjos2372** [comment]
Sample output for the current implementation:
[sample_output.txt](https://github.com/signum-network/signum-node/files/9636262/sample_output.txt)

**Comment by frankTheTank72** [comment]
As disccued we will allow to haven an empty asset-id entry - so we show all tc/trades for one account

**Comment by frankTheTank72** [comment]
@jjos2372 in the current implementation whe have the height in the respone on the order-level.
Can we also get the timestamp from the tranction into the respone.

**Comment by jjos2372** [comment]
What is missing here? The trade timestamp is already available in the `trades` array: https://europe3.testnet.signum.network/burst?requestType=getTradeJournal&asset=13868324881938171674&account=8845697489027354552
```{"account":"8845697489027354552","accountRS":"TS-NMXS-ZZS2-3W9L-9UKJP","asset":"13868324881938171674","tradeJournal":[{"order":"12566023045842374987","asset":"13868324881938171674","account":"8845697489027354552","accountRS":"TS-NMXS-ZZS2-3W9L-9UKJP","quantityQNT":"1000000","priceNQT":"9900","height":455749,"name":"TEST","decimals":4,"price":"99000000","executedQuantityQNT":"1000000","executedVolumeNQT":"9900000000","type":"bid","status":"filled","trades":[{"timestamp":254508866,"quantityQNT":"1000000","priceNQT":"9900","asset":"13868324881938171674","askOrder":"15660969901831666464","bidOrder":"12566023045842374987","askOrderHeight":455749,"seller":"17986607040762404199","sellerRS":"TS-XRD9-TTTL-EVJP-H5C9M","buyer":"8845697489027354552","buyerRS":"TS-NMXS-ZZS2-3W9L-9UKJP","block":"17591006193209370292","height":455749,"tradeType":"buy","price":"99000000"}]}],"requestProcessingTime":11}```

**Comment by frankTheTank72** [comment]
> What is missing here? The trade timestamp is already available in the `trades` array: https://europe3.testnet.signum.network/burst?requestType=getTradeJournal&asset=13868324881938171674&account=8845697489027354552
> 
> ```{"account":"8845697489027354552","accountRS":"TS-NMXS-ZZS2-3W9L-9UKJP","asset":"13868324881938171674","tradeJournal":[{"order":"12566023045842374987","asset":"13868324881938171674","account":"8845697489027354552","accountRS":"TS-NMXS-ZZS2-3W9L-9UKJP","quantityQNT":"1000000","priceNQT":"9900","height":455749,"name":"TEST","decimals":4,"price":"99000000","executedQuantityQNT":"1000000","executedVolumeNQT":"9900000000","type":"bid","status":"filled","trades":[{"timestamp":254508866,"quantityQNT":"1000000","priceNQT":"9900","asset":"13868324881938171674","askOrder":"15660969901831666464","bidOrder":"12566023045842374987","askOrderHeight":455749,"seller":"17986607040762404199","sellerRS":"TS-XRD9-TTTL-EVJP-H5C9M","buyer":"8845697489027354552","buyerRS":"TS-NMXS-ZZS2-3W9L-9UKJP","block":"17591006193209370292","height":455749,"tradeType":"buy","price":"99000000"}]}],"requestProcessingTime":11}```

It should be also the timestamp on the order level - as this is the original creation time

**Comment by jjos2372** [comment]
ok, but the description and your arrow were for the trades only, so the confusion.

**Comment by frankTheTank72** [comment]
Development first round finished
