### ISSUE TITLE
Cannot remove commitment? 

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#659]
![Screenshot_20220910_054421](https://user-images.githubusercontent.com/801414/189483955-f34fec65-feee-4c88-9dcc-3920aad7e216.jpg)
Cannot remove commitment but last block was 5 days, 23 hours ago.

Phoenix says I have to wait 695 blocks.

BTDEX says error 6 not enough funds. 

S-VD7X-759R-6W9U-8PV6R

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/189485088-4767bcaa-258f-4af5-bae8-4c1f29020a38.png)

**Comment by paulpoco** [comment]
Something is broken in the Node software again????

**Comment by jjos2372** [comment]
If an account adds commitment then it becomes blocked again for 4 days. Please confirm if that is the case.

**Comment by paulpoco** [comment]
I think so

**Comment by ohager** [comment]
@paulpoco is it working now?!

**Comment by ohager** [comment]
Closing as @paulpoco confirmed that this is not relevant anymore
