### ISSUE TITLE
New Open API in doesn't include getBlockId API-request

### ISSUE THREAD

**Issue by Frawdie** [signum-network/signum-node#662]
New api-doc in Signum node software doesn't include getBlockId API-request. 

These still works fine.
http://127.0.0.1:8125/burst?requestType=getBlockId&height=1000000
http://127.0.0.1:8125/api?requestType=getBlockId&height=1000000

It seems to me that it's missing from here
[https://github.com/signum-network/signum-node/tree/main/openapi/paths/getters/](url)

But it's included in here at lines 183 and 184
[https://github.com/signum-network/signum-node/blob/main/openapi/signum-api.json](url)

**Comment by ohager** [comment]
done
