### ISSUE TITLE
API `getAccountTransactions` does not includes `Add treasury account` results

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-node#668]
When using the api `getAccountTransactions`, the results does not include the user transaction type 2, subtype 7: "Asset Add Treasury Account".

To look into details, please check on mainnet:
transaction: 17107203007601209777

then get try to get that transaction using getAccountTransactions
account: S-MXER-PULR-T3N3-ALA5F
type: 2
subtype: 7

No transaction is returned... (sorry not found a similar transaction on testnet to check if it is already fixed on 3.5.1-beta1)

**Comment by frankTheTank72** [comment]
I used  /api?requestType=getAccountTransactionIds for account 12548624695006197143:

tx is in:

{
  "transactionIds": [
    "4026320984271529922",
    "14177079671813153491",
    "15351360403438129586",
    "5355023385448750020",
    **"17107203007601209777",**
    "13461483523530366796",
    "5916699236260081005",
    "3389932596695136158",
    "3173942018658913660",
    .....

**Comment by frankTheTank72** [comment]
found it also in the call getAccountTransactions

[12548624695006197143.txt](https://github.com/signum-network/signum-node/files/9668745/12548624695006197143.txt)

**Comment by frankTheTank72** [comment]
![grafik](https://user-images.githubusercontent.com/39116221/192883398-d2b61201-22ca-404d-be87-a5cf94a1103c.png)

**Comment by jjos2372** [comment]
For this particular transaction, sender and recipient are the same account, that might be the source of the problem with that particular request.

**Comment by deleterium** [comment]
Using the ID it works, but using the RS-Address, not.
