### ISSUE TITLE
Missing asset properties at API `getAssetsByIssuer`

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-node#669]
When getting the assets in that way, the response assets does not include properties:
* `quantityBurntQNT`
* `quantityCirculatingQNT`
* `numberOfTrades`
* `numberOfTransfers`
* `numberOfAccounts`

It is expected that these info are included, similar to a getAsset response. Example:

getAsset | getAssetsByIssuer
-- | --
"account": "13592187744525340181", | "account": "13592187744525340181",
"accountRS": "TS-MMJP-RNWF-QWLZ-D8BAT", | "accountRS": "TS-MMJP-RNWF-QWLZ-D8BAT",
"publicKey": "f3b1ac...", | "publicKey": "f3b1ac...",
"name": "TEST", | "name": "TEST",
"description": "Just another test asset.", | "description": "Just another test asset.",
"decimals": 4, | "decimals": 4,
"mintable": false, | "mintable": false,
"quantityQNT": "10000", | "quantityQNT": "10000",
"quantityBurntQNT": "0", |  
"asset": "12838010428090646198", | "asset": "12838010428090646198",
"quantityCirculatingQNT": "10000", |  
"numberOfTrades": 0, |  
"numberOfTransfers": 0, |  
"numberOfAccounts": 1, |  
"volumeQNT": "0", | "volumeQNT": "0",
"priceHigh": "0", | "priceHigh": "0",
"priceLow": "0", | "priceLow": "0",
"priceOpen": "0", | "priceOpen": "0",
"priceClose": "0", | "priceClose": "0"

**Comment by jjos2372** [comment]
Should be fixed with that commit.
