### ISSUE TITLE
OpenAPI  label  Get open Bid/ask Orders

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#673]
Pleae adjust the label for 

- getAllOpenBidOrders
- getAllOpenAskOrders

from

- Get Open Ask Orders
- Get Open Bid Orders

to

- Get **All** Open Ask Orders
- Get **All** Open Bid Orders

![grafik](https://user-images.githubusercontent.com/39116221/193901108-f92f0ef0-0b2e-4fb9-8573-ded6a688ea7a.png)

**Comment by ohager** [comment]
echt jetzt?!

**Comment by frankTheTank72** [comment]
yes :-)
