### ISSUE TITLE
Add the possibility to get tokens by name

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#674]
We are getting more and more tokens created on the chain :partying_face:  - and though it becomes each time more difficult to easily search the tokens. It should be possible to search tokens by their name, knowing that token names are not unique.... but this feature can help us to find token quickly.

> should be a like select to consider parts of the name

**Comment by jjos2372** [comment]
Current solution is case sensitive and is being wrapped with %..%.

We should discuss if we should make it case insensitive and also if we should go only for ..%.

**Comment by deleterium** [comment]
We could allow `*` on search. If no `*`, then default to `...%`
