### ISSUE TITLE
Missing messages block in API `sellAlias` (open-api)

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-node#675]
It is possible to add messages and note to self in transaction. These fields are not documented in api-doc. I'm not sure about MessageData / encryptToSelfMessageData, because these fields seems not to be implemented in classic wallet.

message
messageIsText
messageToEncrypt
messageToEncryptIsText
encryptedMessageData
encryptedMessageNonce
messageToEncryptToSelf
messageToEncryptToSelfIsText
encryptToSelfMessageData
encryptToSelfMessageNonce

Here is a example of transaction sell alias with note to self: https://t-chain.signum.network/tx/8192420397308865036

**Comment by deleterium** [comment]
Same on `buyAlias`

Example TX: [1831202506654360496](https://t-chain.signum.network/tx/1831202506654360496#)

**Comment by ohager** [comment]
jfyi: https://github.com/signum-network/signum-node/blob/main/openapi/README.md

**Comment by ohager** [comment]
done
