### ISSUE TITLE
Open-api `addAssetTreasuryAccount` has incomplete/wrong information

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-node#676]
1) The field `referencedTransactionFullHash` is mandatory, but it isn't marked (no orange mark).

2) This statemet is incorret: `Mind, that Smart Contracts cannot be marked as treasury accounts`. The contracts cannot mark other accounts as treasury, but they can be marked as treasury for assets issued by regular accounts.

**Comment by ohager** [comment]
jfyi: https://github.com/signum-network/signum-node/blob/main/openapi/README.md

**Comment by ohager** [comment]
done
