### ISSUE TITLE
New Open API doesn't include getECBlock API-request

### ISSUE THREAD

**Issue by Frawdie** [signum-network/signum-node#678]
New api-doc in Signum node software doesn't include getECBlock API-request.

These still works fine.
http://127.0.0.1:8125/burst?requestType=getECBlock
http://127.0.0.1:8125/api?requestType=getECBlock

I can't find it from any files realted to new api-doc but it's included in legacy api-doc.

![image](https://user-images.githubusercontent.com/86055251/195980404-d6b578df-5188-40be-afc6-46846af204ff.png)

**Comment by ohager** [comment]
This is true. Due to the sheer amount of work for the API Doc some calls were kept undocumented as they are of no or unknown use. Tbh, I even don't know if EC blocks are of any relevance for Signum. This seems to be an relict from the NXT code base. Maybe @jjos2372 or @deleterium can shed some light on this?!

@Frawdie do you use this call for something, or do you even know what EC Blocks are?

**Comment by Frawdie** [comment]
> This is true. Due to the sheer amount of work for the API Doc some calls were kept undocumented as they are of no or unknown use. Tbh, I even don't know if EC blocks are of any relevance for Signum. This seems to be an relict from the NXT code base. Maybe @jjos2372 or @deleterium can shed some light on this?!
> 
> @Frawdie do you use this call for something, or do you even know what EC Blocks are?

No I don't use that at all. And no I don't know what those EC blocks are. Just noticed that it isn't in api-docs and created this issue. I didn't know that there were calls which intentionally were excluded from new api-docs. I totally understand why excluding were done. 

But I would wan't to know what those EC Blocks are if someone could enlighten me, please.

**Comment by ohager** [comment]
Yes, some functions (maybe 4 or 5) are intentionally undocumented, mostly for two reasons:

- I simply don't know what the function is doing or what is it for 
- The function is unused/makes not much sense nowadays (like generateToken)

According to @jjos2372 the ECBlock has a relevance and I'll keep this issue open:

```
[...] the EC stuff is to prevent a transaction created in a fork to be confirmed. So, if your node creates a transaction while in a fork, it will not confirm. The same is valid to avoid "replay" attack in case we have more than one chain running.
```

**Comment by ohager** [comment]
Addition: The EC stands for Economic Clustering. It's from the beginning of the chain and was introduced from NXT.

Mentioned here shortly:

https://nxtforum.org/news-and-announcements/development-roadmap-update-2014-07-05/
https://nxtforum.org/general-discussion/on-economic-clusters-and-the-longest-chain/

definitely, I will dive into that feature to understand a bit better.

**Comment by ohager** [comment]
done
