### ISSUE TITLE
Confusing naming in new api-doc

### ISSUE THREAD

**Issue by Frawdie** [signum-network/signum-node#679]
Hi!

I wanted to point out that these are really confusing in my humble opinion.

This Get Blockchain Info is doing getBlockchainStatus api request to the node
![image](https://user-images.githubusercontent.com/86055251/195982513-7c9f076f-1d99-4a98-ac6f-8ad0c7239b6e.png)

This Get Blockchain Status is doing getState api request to the node
![image](https://user-images.githubusercontent.com/86055251/195982544-9a421d34-90a3-4ede-8952-522196bedbad.png)

Get Blockchain Status in new api-doc isn't doing getBlockchainStatus api request and I find that confusing should one or another be renamed?

**Comment by ohager** [comment]
I agree.... I struggled also, but already with the "original" RPC names: `getState` vs `getBlockchainStatus`. Do you have suggestions for better aka more precise names? 

Maybe `getState` can be renamed/titled as `Get Node Info`, as it also returns details of the node.

Or: `Get Blockchain Details`? 

Wdyt?

**Comment by Frawdie** [comment]
I think that Get Blockchain details  could be getState api requests name. That is  descriptive name IMHO.

**Comment by deleterium** [comment]
If they are a subset, then I would go with **get Blockchain Info** and **get Extended Blockchain Info**

**Comment by Frawdie** [comment]
> If they are a subset, then I would go with **get Blockchain Info** and **get Extended Blockchain Info**

That would be better option because getState includes all the info from getBlockchainStatus and more. So it would be the Extended one.

**Comment by ohager** [comment]
done
