### ISSUE TITLE
Add more info in the README about how to setup MariaDB

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#690]
Add more info in the README about how to setup MariaDB.

I did exactly what the README said to do, what now?  What to do to MariaDB after you install it?  How to get it running?  etc etc

**Comment by paulpoco** [comment]
Ok got it working.

Blew away database I made with command line.

Used HeidiSQL interface --> created a new user called "signum" and gave all rights --> then created a database called "signum" ---> then ran the windows node exe.
![image](https://user-images.githubusercontent.com/801414/201496368-0a310cc6-820e-4c2d-9fe2-43f22d717a2e.png)

**Comment by paulpoco** [comment]
https://signum.community/signum-node-installation/ this page need updating but it makes sense just using user=signum and database=signum
![image](https://user-images.githubusercontent.com/801414/201497068-029a5b78-b4d8-4c2e-ae7b-3afbbacb15b2.png)

**Comment by frankTheTank72** [comment]
i think so - close it - if not reopen pls
