### ISSUE TITLE
Develop SIP-43 Token owner

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#697]
Requirements defined here -->   https://github.com/signum-network/SIPs/blob/master/SIP/sip-43.md

Current Owner will be checked by the new transaction type/subtype (if exists)
Sender = current owner / receiver = new owner ;  ref-tx to use for identify the token

API spec:
account = current owner 
issuer = original creator
issuerRS = account address
cover new transaction type/subtype

Explorer
Handling new tx type/subtype
Showing current owner

Classic/ Phoenix/ XT-Wallet
Handling new tx type/subtype

Signumswap
Adding function to transfer ownership

SC functions:
Retrieve position of an given address - example : getAssetBalance(address, token-id)
Get cirulation of a token - example : getCirculation(token-id)

**Comment by jjos2372** [comment]
There is already a `getAssetCirculating` in the virtual machine. So only missing is requesting the balance of a given address.

**Comment by ohager** [comment]
done
