### ISSUE TITLE
Fast blocks is an issue, see examples in SIP-27

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#702]
Fast blocks is an issue, see examples in SIP-27.

When the block round ends early due to fastblocks, miners are not done scanning their plots.

Now if the miner is set to send all, then they may send their very 1st deadline found that is really high, then the round ends early due to a fast block.  This will affect the miner's size and their effective size will drop a lot from this fast block deadline.

And if miner is set to send only best at the end of scanning, a fast block happens, the miner then misses a deadline.  Enough of these and they will drop below the Pools grace deadlines.

Please implement BTFG's proposed fix in the next hard fork.

**Comment by pir8radio** [comment]
fast blocks can be an issue..   but its an issue for "some" miners...    the block can not be processed if there is no miner to process it..  so if a miner submits a valid deadline, is there a network problem?         Or are we saying we will only accept deadlines within a  small window    3.XX-5.XX ?   couldnt that cause issues?

**Comment by damccull** [comment]
I don't think there can be a fix for short blocks. It's a luck of the draw. Some blocks are long too. It's an average of 4 minute block time. My suggested fix would be on the pool level for the second issue with pools. They should keep track of the average submissions and only penalize if many of the deadlines are submitted late.

As for the effective size, I'm not sure how to handle that one. Can you link to the proposal?

**Comment by frankTheTank72** [comment]
2 years old - I close the issue - please reopen it if it is still valid
