### ISSUE TITLE
add `nextIndex` to further paginable requests, like getAliases

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#708]
Partially, the API returns an additional field `nextIndex` in its response, but it's not returned in a consistent way.

At this moment, the following requests do not return `nextIndex`

- getAccountTransactions
- getAliases

> More to investigate

**Comment by ipr0310** [comment]
The request `getAliasesOnSale` should also be considered

**Comment by jjos2372** [comment]
Implemented the following at https://github.com/signum-network/signum-node/commit/35f86c21ce477b560861cd45e144b534fb825880:
- [x] getAccountTransactions
- [x] getAccountTransactionIds
- [x] getAliases
- [x] getAliasesOnSale

Please comment on other endpoints that need to be adjusted.
