### ISSUE TITLE
Option to get transaction between accounts

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-node#712]
Problem: Currently if I want to get transaction between accounts, I need to use **getAccountTransactions** from some account and then search the other account in these transactions. So I need to get a high number of transactions to ensure that the desired transactions will be present.

Proposal:
1) Add fields `sender`, `recipient` and `bidirectional` to the **getAccountTransactions** and **getAccountTransactionsIds**
2) If `account` is provided, `sender`, `recipient` and `bidirectional` are ignored (compatibility mode)
3) If `account` is not provided, at least one of `sender` or `recipient` must be provided
3) `bidirectional` default is false, so only transactions from `sender` to `recipient` will be returned.
3) If `bidirectional` is true, transactions from `recipient` to `sender` will also be returned
3) Empty field for `sender` (or `recipient`) means that any sender (or recipient) should be returned in the transactions.

It would help a lot in dApp if we had these options to get transactions between some logged user and one smart contract. It would also helps to get transactions between accounts.

**Comment by DevPJ9** [comment]
Hello @jjos2372 I would like to work on this.

**Comment by ohager** [comment]
solved
