### ISSUE TITLE
add `description` to subscriptions-related requests

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-node#718]
Most API request related to getting subscription information like `getAccountSubscriptions`, `getSubscriptionsToAccount`, `getSubscription` provide basic data of a subscription, but it does not provide the ``Description`` property.

The ``description`` property should be added.

``Subscription description + SRC-44`` would help a lot in use cases that can use the subscription feature, it provides the subscription a way to have a branding.

The request that would need the improvements are the following:
-  getAccountSubscriptions 
- getSubscriptionsToAccount
- getSubscription

**Comment by DevPJ9** [comment]
Hello @ipr0310. I would like to work on it.

**Comment by jjos2372** [comment]
Should this description come from the transaction (message) that created the subscription?

**Comment by frankTheTank72** [comment]
> Should this description come from the transaction (message) that created the subscription?

yes

**Comment by jjos2372** [comment]
any potential messages attached to the subscription creation is now returned as an *attachement* (as they are shown in a regular transaction)
