### ISSUE TITLE
Add the option of obtaining past-payments from a specific subscription.

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-node#719]
As the title says, we should have a way of getting the previous payments from a specific subscription.

As crypto automatic payments are getting more relevant, this is a necessary feature on any subscription-platform.

**Comment by jjos2372** [comment]
We will have a new endpoint called *getSubscriptionPayments* for this.

**Comment by jjos2372** [comment]
So now *getSubscriptionPayments* return the list of transactions for all payments of a given subscription.

If one wants all subscription payments of a given account, then use *getAccountTransactions* with type=21 and subtype=5.

**Comment by ipr0310** [comment]
@jjos2372 I had to re-open this ticket because there is an pagination issue on this request, let me explain:

As you can see on this request, there are more than 65 transaction(Payments)
https://europe3.testnet.signum.network/api?requestType=getSubscriptionPayments&subscription=10129084965209757306

But the issue is happening when i try to make the request with pagination:
https://europe3.testnet.signum.network/api?requestType=getSubscriptionPayments&subscription=10129084965209757306&firstIndex=0&lastIndex=5

You will discover the following on the response:
- You can notice that only 1 transaction is being returned
- You can notice that the `nextIndex` is 6, when in reality only 1 item is being returned

```json
{
    "transactions": [
        {
            "type": 21,
            "subtype": 5,
            "timestamp": 271864410,
            "deadline": 1440,
            "senderPublicKey": "04d794aa453a5bbdb8d580f1d9a76b6d7a25cde0ed38c098550ea0f784d9317a",
            "amountNQT": "1250000000",
            "feeNQT": "1000000",
            "fullHash": "8e26c06fafdcc500bfc4089372ff1129e7dc132ed0220f8a19fb71472d6390a9",
            "transaction": "55693216464250510",
            "attachment": {
                "version.SubscriptionPayment": 1,
                "subscriptionId": "10129084965209757306"
            },
            "attachmentBytes": "017ad613131cbd918c",
            "sender": "13112229684715917355",
            "senderRS": "TS-863D-FNXF-WVPM-DZZXD",
            "height": 527736,
            "version": 1,
            "ecBlockId": "0",
            "ecBlockHeight": 0,
            "cashBackId": "0",
            "block": "2048945161248419226",
            "confirmations": 3,
            "blockTimestamp": 271864629
        }
    ],
    "nextIndex": 6,
    "requestProcessingTime": 19
}
```

**Comment by jjos2372** [comment]
That is the reason we have the `nextIndex`. Not all end points will return exactly the length you asked (when this is filtered in a second pass and cannot be directly filtered by a single sql request). If you follow the `nextIndex` you should be able to iterate over all items. Please check if this is the case, otherwise we have an issue.

**Comment by ipr0310** [comment]
@jjos2372 Is an issue, because you can see on the request that firstIndex is equal to `0` and lastIndex is equal to `5`
The `nextIndex` property is behaving good.

The issue is the amount of ``Payments/Transactions`` that is being  returned is just 1, when in reality, it must return 5 ``Payments/Transactions``
See on this example for postman:
![image](https://user-images.githubusercontent.com/35440957/227285116-9885ba2e-0c20-4bc7-893b-3ef344dd7217.png)

This is the response
```json
{
    "transactions": [
        {
            "type": 21,
            "subtype": 5,
            "timestamp": 271868730,
            "deadline": 1440,
            "senderPublicKey": "04d794aa453a5bbdb8d580f1d9a76b6d7a25cde0ed38c098550ea0f784d9317a",
            "amountNQT": "1250000000",
            "feeNQT": "1000000",
            "fullHash": "2235620d09a48bdf66474f99056e603c24b76605e52ab19ff0d094e4046bc48e",
            "transaction": "16108148851006911778",
            "attachment": {
                "version.SubscriptionPayment": 1,
                "subscriptionId": "10129084965209757306"
            },
            "attachmentBytes": "017ad613131cbd918c",
            "sender": "13112229684715917355",
            "senderRS": "TS-863D-FNXF-WVPM-DZZXD",
            "height": 527752,
            "version": 1,
            "ecBlockId": "0",
            "ecBlockHeight": 0,
            "cashBackId": "0",
            "block": "10398869759887365253",
            "confirmations": 2,
            "blockTimestamp": 271868846
        }
    ],
    "nextIndex": 6,
    "requestProcessingTime": 88
}
```
