### ISSUE TITLE
API getBlock is missing cumulativeDifficulty lookup

### ISSUE THREAD

**Issue by gittrekt** [signum-network/signum-node#720]
cumulativeDifficulty is currently only available in getState and getBlockchainStatus. It's available in the block table so should be able to be reported when using the getBlock/getBlocks lookup.

**Comment by frankTheTank72** [comment]
@jjos2372  maybe simple to add for 3.7.0 ?

**Comment by jjos2372** [comment]
Fixed, will be on the next release.
