### ISSUE TITLE
Allow to gets assets by account ownership

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-node#727]
**Describe the solution you'd like**
As the new incoming Signum Node Version will include a new transaction type `Token Ownership Transfer` adjustments are necessary.
Is necessary to add support for getting the assets only ``owned`` by an account, not the issued ones.

What i mean with `ownership` is that the account is able to do basic token operations like: Minting, Treasury account management, etc...

**It would look something like this:**
![image](https://user-images.githubusercontent.com/35440957/223002778-e88b505b-96f0-40f6-8d99-aa45bf9a2bf0.png)

**Additional Context**
There is the possibility to get assets by issuer `(getAssetsByIssuer)` but not by ownership.

**Alternative option**
Is possible to get the assets an account ``Has ownership of`` by just making a `getAssetsByIssuer` request and filter it client-side. 
But by the time the chain grows, efficiency is still key.

**Comment by frankTheTank72** [comment]
@jjos2372 the current call /api?requestType=getAssetsByIssuer is not returning the correct account ( always the issuer) - can you adjust the output like on getAsset please

**Comment by frankTheTank72** [comment]
I would go for the alternative option to add a flag "isOwner" by default it is false - so it shows all issued tokens - if it set to true it will show all tokens with account = searched account

**Comment by jjos2372** [comment]
Should we create a new end point like *getAssetsByOwner* as suggested or just extend this one and make *getAssetsByIssuer* to return both, issued and owned?

**Comment by frankTheTank72** [comment]
i would think it is mroe clear to have _getAssetsByOwner_ and _getAssetsByIssuer_

**Comment by frankTheTank72** [comment]
@ipr0310 fixed with beta2 and also new _**getAssetsByOwner**_
