### ISSUE TITLE
Create a new API for retrieving smart contract data by machineCodeHashId

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#732]
We should have an API call (paginated) which returns by machineCodeHashId all existing smart contracts on chain.
The output per SC should be the same as from the API call getAT

Proposal for the name : **getATsByMaschineCodeHashId**

**Comment by ohager** [comment]
I recommend to cal it simply `requestTypes=getATs`

with the following parameters:

- `machineCodeHashId`
- `timestamp`
- `startIndex`
- `lastIndex`
- `includeMachineCode` (default: false) 
- `includeCreationMachineData` (default: false)

the both latter reduces response payload significantly, if set to false.

**Comment by frankTheTank72** [comment]
I would go for the simplification and just use the same parameter

**Comment by jjos2372** [comment]
In that case, maybe better to have just `getAccountATs` and then leave the account empty if you want it for any account? Because the code will be exactly the same.

**Comment by ohager** [comment]
done and live

https://europe3.testnet.signum.network/api-doc/index.html#get-/api-requestType-getATs
