### ISSUE TITLE
Update Open-api information on `subscription-related` requests

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-node#733]
As the following tickets were solved: https://github.com/signum-network/signum-node/issues/710 https://github.com/signum-network/signum-node/issues/718 
Which means that now is possible to get the ``description/attachment`` or ``alias (renewal fee details)`` of a subscription on the following requests:
- getAccountSubscriptions
- getSubscriptionsToAccount
- getSubscription

The proper solution would be to update the `response/example` schema on the requests mentioned above:
![image](https://user-images.githubusercontent.com/35440957/227256602-e7c4a742-0f41-41be-89d6-24cb729932d4.png)

**The following are 2 examples:**

**This is an example of an attachment:**
```json
{
  "id": "16110513677706376296",
  "sender": "13112229684715917355",
  "senderRS": "TS-863D-FNXF-WVPM-DZZXD",
  "recipient": "14978592240935099976",
  "recipientRS": "TS-RRLA-B3Y7-L4EU-E8PRZ",
  "amountNQT": "100000000",
  "frequency": 3600,
  "timeNext": 271863837,
  "timestamp": 270240237,
  "attachment": {
    "version.Message": 1,
    "message": "signa 1",
    "messageIsText": true
  },
  "requestProcessingTime": 7
}
```
**This is an example of a subscription which its purpose is renewal fees for alias**
```json
{
      "id": "10214955016669843369",
      "sender": "13379979993382958865",
      "senderRS": "TS-TFSK-X9RQ-6WDQ-DWTDM",
      "recipient": "0",
      "recipientRS": "TS-2222-2222-2222-22222",
      "alias": "10214955016669843369",
      "aliasName": "galaxy",
      "tld": "0",
      "tldName": "signum",
      "amountNQT": "1250000000",
      "frequency": 1440,
      "timeNext": 271864313,
      "timestamp": 263485758
    }
```

**Comment by ohager** [comment]
https://europe3.testnet.signum.network/api-doc/index.html#get-/api-requestType-getSubscriptionsToAccount
https://europe3.testnet.signum.network/api-doc/index.html#get-/api-requestType-getAccountSubscriptions
https://europe3.testnet.signum.network/api-doc/index.html#get-/api-requestType-getSubscription

all done and live!
