### ISSUE TITLE
Classic wallet is not getting copied for the Docker version h2 and maria

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#737]
There is only update phoenix.sh and missing the sh part that copies the classic wallet
https://github.com/signum-network/signum-node/commit/d8d4f030a7c01117cf943998c085a8b37443641d

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/231342235-f7ea1cc3-bd25-4771-8539-8bf034c7aa66.png)

And this are 2 different names, how do the ci versions get into the Dockerfile?
![image](https://user-images.githubusercontent.com/801414/231342463-7a934819-6bd2-4e22-b664-b7ab31b3ea41.png)

**Comment by paulpoco** [comment]
@ohager I tried updating the Dockerfiles to add the classic wallet, well I don't quite have it correct.   When you have time could you look it?
![image](https://user-images.githubusercontent.com/801414/231643626-d939cd9d-0f58-4446-8854-e749f460cd02.png)

**Comment by ohager** [comment]
thanks for reporting... will look into it.

**Comment by ohager** [comment]
This issue is obsolete.... Classic wallet is EOL and we'll move to Neo. Next major release comes with Neo Classic built in.

> btw: I suggest to call Neo Classic only Neo @deleterium
