### ISSUE TITLE
allow getAccountBalance for Burn Account (or return burnt SIGNA in getState)

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#739]
### Problem
as for the total supply reported to CMC we use `totalMinedNQT` from `GET /api?requestType=getState`, but would be good to report a value where burnt SIGNA is being subtracted from. Unfortunately, the endpoints `getAccount` and `getAccountBalance` do not allow `0` account.

### Solutions
1. add `burntNQT` to `getState` method
2. allow `getAccount` and/or `getAccountBalance` for Burn Account

> Ideally, both makes sense

**Comment by frankTheTank72** [comment]
maybe also add totalSupply into the getStae which already does the work minted - burned

**Comment by jjos2372** [comment]
Added some more stuff to `getState`, below for testnet:
```
  "totalMinedNQT": 199258764100000000,
  "totalBurntNQT": 55409445190405,
  "circulatingSupplyNQT": 199203354654809600,
```
