### ISSUE TITLE
allow `getATMapValues` to be returned in reversed order

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#740]
### Problem
With the new staking contract we store e.g. totalStake per block height and also distributions per block height in the AT/SC maps. But the first element is the first (oldest) entry, which will cause a problem when we want to show only the most recent stakes or distributions (i.e. necessary for APR calculation). With ongoing time we would need to use the pagination to get the latest/most recent values, thus causing more work load for the nodes.

### Solution
Introduce a flag `reversedOrder` that permits a response in reversed order. 

> Looking into the database, I can see that `height` is being stored. So, this can be used as order key

**Comment by jjos2372** [comment]
Actually we have already it using the height as descending order:
https://github.com/signum-network/signum-node/blob/ee472541f2122c31b45329e3c44e09cdd018ff24/src/brs/db/sql/SqlATStore.java#L235

Isn't that what was asked?

**Comment by ohager** [comment]
haeh? Last time I looked into it I got another order...ok. closing
