### ISSUE TITLE
Referential integrity constraint violation

### ISSUE THREAD

**Issue by josergc** [signum-network/signum-node#750]
![image](https://github.com/signum-network/signum-node/assets/7774952/c92e45ef-84ec-4433-b13c-34818b4f3f50)

I've been facing this problem from a while now.
Restarting the node doesn't fix the problem and I have to resync the whole database or use a backup.
It uses H2 database modality.
Node version 3.7.1
The GUI hangs, so I can't select the text, I only can take screenshots.

**Comment by ohager** [comment]
Yeah, we will update to newest H2 version (V2) soon. The old V1 is known to have issues with large files. For Mainnet we currently recommend to go with MariaDB, which has no issues with a large base.

**Comment by josergc** [comment]
for any weird reason, when I've tried MariaDB (installed via XAMPP), it's performance was slower than H2

**Comment by ohager** [comment]
yeah, we see slower syncing performance on MariaDB. We are also thinking of adding Postgres as another option. I plan to experiment with it next month. Atm, I have a bunch of things cooking...

**Comment by josergc** [comment]
I'd like to add that this problem happens in the version 3.7.2, when going to start the next block after making a transfer coins op through web GUI pops a red framed message saying that the transaction got timeout, and I may check later if the transaction actually happened.
![image](https://github.com/signum-network/signum-node/assets/7774952/8c339b31-360c-41d2-b60d-93ea36a6d372)

**Comment by ohager** [comment]
This should be fixed since 3.7.3
