### ISSUE TITLE
Ability to filter transactions by recipient and/or sender

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#753]
At the moment, we can filter transactions only by type and subtype. But it would simplify (and also reduce node workload) if it would be possible to filter by sender and/or receiver only.

This would require a node api change for `getAccountTransactions` and adding parameters  `senderId` and `recipientId`.
This could also be done for `getUnconfirmedTransactions`

**Comment by deleterium** [comment]
Is this duplicated from #712 ?

**Comment by ohager** [comment]
solved
