### ISSUE TITLE
Manage node from HTTP API

### ISSUE THREAD

**Issue by Wekuz** [signum-network/signum-node#755]
Add an endpoint to the HTTP API, so it would be possible restart or stop the node from the API. 
The endpoint could look something like this:

**Endpoint:**
POST /api?requestType=restartNode
**Parameters:**
- apiKey (string)
<br/>

**Endpoint:**
POST /api?requestType=stopNode
**Parameters:**
- apiKey (string)

**Comment by ohager** [comment]
I'm hesitant to add such "powerful" system call to the api. This shouldn't be done via API call, but via some server side access. This should be discussed with the community. @jjos2372 what's your opinion about this?

**Comment by ohager** [comment]
@frankTheTank72 any comment on this. I don't like the idea to expose such feature. IMHO, it can be solved with OS tools.

**Comment by Wekuz** [comment]
Yeah, nvm controlling your node using something like SSH is sounds much better (I am doing it this way myself). I just tought it would maybe add extra functionality to the API, but I see it's unnecessary. I think I will close this.

**Comment by ohager** [comment]
Just to complete here: Shutting down the node may take some time, especially for H2 and (recommended ) defragmentation enabled. But, maybe it's about monitoring the node...there are some raw/rough tools to monitor the node, but maybe that part should get more attention in general.
