### ISSUE TITLE
WS Port shown wrong on Node startup

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#777]
I set up port umber 443 for Http API and Web Socket is showing up as 443+1, although it should show the correct port 8126 (not set explicitely in the node.properties)

The connection works under 8126 (default port)

```
[INFO] 2024-01-18 15:30:12 brs.peer.Peers - Started peer networking server at 0.0.0.0:8123
[INFO] 2024-01-18 15:30:12 brs.web.server.WebServerImpl - Started Http API server at 0.0.0.0:443
[INFO] 2024-01-18 15:30:12 brs.web.server.WebServerImpl - Started [EXPERIMENTAL] Websocket API server at 0.0.0.0:444
```

**Comment by damccull** [comment]
Is WS server still experimental? This logging issue seems like a simple fix and I will take a look at it if I get time and if it's just a quick change. I don't yet understand how web sockets work though so any actual work on those is still beyond my ability.

**Comment by ohager** [comment]
It is still experimental. For this issue I will provide a fix in a few moments. I tested the WS connection heavily and in general it's working. The only issue I found so far: Sometimes the graceful shutdown throws exception in the Debouncer (Timer already cancelled), and missing WSS support, which is needed when using within a HTTPS page.
