### ISSUE TITLE
OpenAPI doc - use `getBlockchainStatus` to fetch the Node version 

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#778]
Currently, it uses the veeeery slow `getState` call... `getBlockchainStatus` is waaaaay faster.

**Comment by damccull** [comment]
How is this built? A separate js app served by the node? Or can it be made to just include the version as injected by Java code during the render to client?

**Comment by ohager** [comment]
short answer: own build pipeline.
long answer: https://github.com/signum-network/signum-node/blob/main/openapi/README.md
