### ISSUE TITLE
misleading comment in 3.8.0 node-default.properties using H2

### ISSUE THREAD

**Issue by josergc** [signum-network/signum-node#781]
the new version 3.8.0, if nothing is specified for the `DB.Url` property, the value `jdbc:h2:file:./db/signum-v2;DB_CLOSE_ON_EXIT=TRUE` is internally used which will defrag the db on node shutdown. In the comment of the `node-default.properties` file, this appears as `DB.Url=jdbc:h2:file:./db/signum;DB_CLOSE_ON_EXIT=FALSE`. If the node is stopped and this line is uncommented to be used as the connection string to no defrag the db on close then, the next time the node is started, the node will start to sync from scratch because the file name is different. Oneself needs to realize that the file in the `db` folder has different name due the version upgrade of H2.

**Comment by damccull** [comment]
@josergc this seems like a fantastic first issue to solve. Have you considered making a pull request which solves this issue?

**Comment by damccull** [comment]
Aww man. I was hoping to encourage new developer volunteers lol.

**Comment by josergc** [comment]
thank you @ohager ! sorry @damccull  , I cloned the repo but later the weekend arrived and no spare time to do the modification 😅

**Comment by damccull** [comment]
Heh. No problem. Please continue to contribute as you can!
