### ISSUE TITLE
https://signum.community/signum-snr-awards/ broken link?

### ISSUE THREAD

**Issue by josergc** [signum-network/signum-node#793]
The link is found at the node-default.properties and it redirects to https://www.docage.com/redirect?from=signum.community that has no info in regards the SNR rewards.
Please check this out:
```
curl -i https://signum.community/signum-snr-awards/
HTTP/1.1 301 Moved Permanently
Date: Thu, 01 Feb 2024 06:29:42 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 262
Connection: keep-alive
Server: Apache
Location: https://www.docage.com/redirect/?from=signum.community

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.docage.com/redirect/?from=signum.community">here</a>.</p>
</body></html>
```
![image](https://github.com/signum-network/signum-node/assets/7774952/0f88bade-1305-41a8-b7e9-8394fe7904ad)

**Comment by ohager** [comment]
The maintainer of the community is not active anymore... we have this documented in another place: https://docs.signum.network/signum/activate-snr

Need to check, why this is in the node.properties at all
