### ISSUE TITLE
Node stuck at Block 1237958 and Blacklisting all peers

### ISSUE THREAD

**Issue by Zwurg** [signum-network/signum-node#797]
Hello,

my Node stuck with this Message.

[INFO] 2024-02-02 15:26:19 brs.peer.PeerImpl - Blacklisting 82.0.25.117 (v3.7.3) because of: pulled invalid data using getCumulativeDifficulty
[INFO] 2024-02-02 15:26:22 brs.BlockchainProcessorImpl - Failed to parse block: Peer base target 6035027302408758296, expected is 6035010238503691288, peer 98.110.169.214
[SEVERE] 2024-02-02 15:26:22 brs.peer.PeerImpl - Reason for following blacklist: Peer base target 6035027302408758296, expected is 6035010238503691288, peer 98.110.169.214
[INFO] 2024-02-02 15:26:22 brs.peer.PeerImpl - Blacklisting 98.110.169.214 (v3.7.2) because of: pulled invalid data using getCumulativeDifficulty
[INFO] 2024-02-02 15:26:29 brs.BlockchainProcessorImpl - Failed to parse block: Peer base target 6035027302408758296, expected is 6035010238503691288, peer wekuz-signa-node.duckdns.org:8123
[SEVERE] 2024-02-02 15:26:29 brs.peer.PeerImpl - Reason for following blacklist: Peer base target 6035027302408758296, expected is 6035010238503691288, peer wekuz-signa-node.duckdns.org:8123
[INFO] 2024-02-02 15:26:29 brs.peer.PeerImpl - Blacklisting 158.179.201.70 (v3.8.0) because of: pulled invalid data using getCumulativeDifficulty

I have tryed with pop of 100  Blocks and downgrade to Version 3.7.3 but it stuck always at the same Block.

**Comment by frankTheTank72** [comment]
Can you set in your config  with 3.8.0 the following

P2P.NumBootstrapConnections = 2

instead 3 .. this should help

**Comment by Zwurg** [comment]
Thanks, but it dosent help.

The Problem is the same.

But why says the massage that the base target isnt the expectation and blacklisting because pulled invalid data using getCumulativeDifficulty ?

**Comment by damccull** [comment]
> Thanks, but it dosent help.
> 
> The Problem is the same.
> 
> But why says the massage that the base target isnt the expectation and blacklisting because pulled invalid data using getCumulativeDifficulty ?

The node chooses which fork to follow based on the highest cumulative difficulty. It's the tie breaker. You likely got onto a fork from a node that has since resolved itself and now you're too far to automatically pop blocks. You can use the API to manually pop blocks but I'm not sure how. Anyone got instructions on that @ohager or @frankTheTank72 ?

**Comment by ohager** [comment]
We have to add a troubleshooting section somewhere in the docs.... better doing this redundantly. Like here on GH and also on the official docs

https://docs.signum.network/signum

**Comment by ohager** [comment]
Btw: we will update the bootstrap node list  in the next release. It looks like the outdated list and certain configs on the featured nodes needed to be updated. t should be less stucky in the near future.

Look here: https://github.com/signum-network/signum-node/pull/804/files#diff-e53e56aa8d9b4021d0bb75c4dba8304feaff712c511b73c9d69277609c6dd850R78

**Comment by ohager** [comment]
Sqlite is the way to go for embedded dbs.. New with version 3.8.1

Closing
