### ISSUE TITLE
Heavy I/O with sqlite on Windows

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#817]
When I use sqlite on windows PC my I/O starts to go up to 100% and the sync rate is very slow.
Seems the sqlite is by default in FULL synchronous mode.

I should be able to set PRAGMA synchronous = OFF as parameter for the session.

Please add this paramter to the config in the node. (like WAL)

Hint
On Ubuntu it seeems to work fine

**Comment by frankTheTank72** [comment]
Maybe also add PRAGMA cache_size -2000 parameter to define the cache

**Comment by ohager** [comment]
this should be "solved" using #819
