### ISSUE TITLE
v3.7.3 cannot sync with network; was 3.8.1 hardfork?

### ISSUE THREAD

**Issue by PSLLSP** [signum-network/signum-node#822]
I still run `Signum Node` v3.7.3 and it was working fine but it seems it cannot sync with network for 3 or 4 days.

My node was not upgraded because version v3.8.0 requires newer MariaDB than could be installed on my system (I have 10.3, but 10.6+ is required) and upgrade to version v3.8.0 was not mandatory. I was not upgrading to v3.8.1 because there is an information that it is not hardfork and I see that it still has some experimental features; SQLite support is interesting one but that one is still marked as experimental...

Anyway, it looks like my node lost synchronization few days ago (it is up and running for a month):

```
$ signumhealth -n http://localhost:8125

2024-05-13T18:11:59.743Z
http://localhost:8125 - height: 1270724
https://europe.signum.network - height: 1276697
Node [http://localhost:8125] is 5973 block(s) behind of Node [https://europe.signum.network] - syncing...
Signature Check:
http://localhost:8125 - signature (height: 1270724): 10dd9403b6f62cbb7462925c8b5c211d22bd13c947e12f50e974e15486c0e108408192053205ed2211c9f73afa8c37be5e9571eb2af58b114dd9a6dfe3cc0dec
https://europe.signum.network - signature (height: 1270724): 74465018969e40ca166115a4c1d6758cfd7f2c65351f711b415929e8ac29e00e608ceac7b612cf27df479d0760890bc77fde06bada58ef3495784bd839ee06cb
❌ 2024-05-13T18:11:59.878Z Health Check failed Node [http://localhost:8125] is forked from [https://europe.signum.network] - Try popping off to get in sync again
```

This is console output, it looks like there was no update for several days:

```
[INFO] 2024-04-21 02:02:03 brs.peer.PeerImpl - Blacklisting 188.34.159.176 (v3.8.0) because of: feeding us a too old fork
[INFO] 2024-04-22 10:18:07 brs.statistics.StatisticsManagerImpl - handling 0.00 blocks/s account_balance cache hit ratio now/total:16.50%/73.45% account cache hit ratio now/total:16.61%/87.01%
[INFO] 2024-04-23 19:43:22 brs.statistics.StatisticsManagerImpl - handling 0.00 blocks/s account_balance cache hit ratio now/total:16.32%/70.83% account cache hit ratio now/total:16.47%/85.75%
[INFO] 2024-04-25 04:53:44 brs.statistics.StatisticsManagerImpl - handling 0.00 blocks/s account_balance cache hit ratio now/total:16.26%/68.45% account cache hit ratio now/total:16.47%/84.54%
[INFO] 2024-04-25 15:00:35 brs.BlockchainProcessorImpl - processed block 1270000
[INFO] 2024-04-26 14:21:44 brs.statistics.StatisticsManagerImpl - handling 0.00 blocks/s account_balance cache hit ratio now/total:16.12%/66.27% account cache hit ratio now/total:16.41%/83.38%
^C[INFO] 2024-05-13 20:33:51 brs.Burst - Shutting down...
[INFO] 2024-05-13 20:33:51 brs.Burst - Do not force exit or kill the node process.
```

After node restart, I see it cannot sync:

```
...
[INFO] 2024-05-13 20:36:21 brs.Burst - Signum Multiverse v3.7.3 started successfully.
[INFO] 2024-05-13 20:36:21 brs.Burst - Running network: Signum
[INFO] 2024-05-13 20:36:24 brs.peer.PeerImpl - Blacklisting 95.84.195.90 (v3.8.1) because of: feeding us a too old fork
[INFO] 2024-05-13 20:36:32 brs.peer.PeerImpl - Blacklisting 89.58.10.207 (v3.8.1) because of: feeding us a too old fork
[INFO] 2024-05-13 20:37:31 brs.peer.PeerImpl - Blacklisting 177.153.50.43 (v3.8.1) because of: feeding us a too old fork
...
```

**Comment by frankTheTank72** [comment]
Try the following in your config:


Please add the following list of BootstrapPeers  to your local or server node to avoid any problems with connecting to the Signum network:

**P2P.BootstrapPeers =**  australia.signum.network:8123; brazil.signum.network:8123; canada.signum.network:8123; europe.signum.network:8123; europe1.signum.network:8123; europe2.signum.network:8123; europe3.signum.network:8123; latam.signum.network:8123; singapore.signum.network:8123; ru.signum.network:8123; us-central.signum.network:8123; us-east.signum.network:8123

**P2P.rebroadcastTo =** 188.26.23.139:8123; 216.114.232.67:8123; 51.235.143.229:8123; signode.ddns.net:8123; 188.34.159.176:8123;signum.mega-bit.ru:8123; storjserver2.cryptomass.de:8123; 89.58.10.207:8123; 84.54.46.176:8123; signumwallet.ddns.net:8123; taylorforce.synology.me:8123; zwurg.feste-ip.net:51940; zmail.cloudns.ph:8123; wallet.signa-coin.eu:8123; wekuz-signa-node.duckdns.org:8123; austria-sn.albatros.cc:8123; signumwallet.lucentinian.com:8123; 85.238.97.205:8123; 124.246.79.194:8123

We will also create a new release for that (3.8.1), so you have it later as a default in your config files.

**Comment by PSLLSP** [comment]
I added peers to node.properties but it doesn't help, my node runs with updated config for several hours and it is still at block 1270724 and rejects all other nodes...

I see now that it rejects v3.7.2, v3.7.3, v3.8.0 and v3.8.1:

```
[INFO] 2024-05-14 14:12:32 brs.peer.PeerImpl - Blacklisting 192.206.141.241 (v3.7.3) because of: feeding us a too old fork
[INFO] 2024-05-14 14:13:47 brs.peer.PeerImpl - Blacklisting 139.99.196.163 (v3.8.1) because of: feeding us a too old fork
[INFO] 2024-05-14 14:13:49 brs.peer.PeerImpl - Blacklisting 216.222.169.149 (v3.8.0) because of: feeding us a too old fork
[INFO] 2024-05-14 14:13:51 brs.peer.PeerImpl - Blacklisting 68.229.232.239 (v3.7.2) because of: feeding us a too old fork
[INFO] 2024-05-14 14:17:40 brs.peer.PeerImpl - Blacklisting 213.221.57.86 (v3.8.0) because of: feeding us a too old fork
```

It looks like I have to delete DB and start sync from block 0...
